// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "PigeonGenerated.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation RxMetadataStatusBox
- (instancetype)initWithValue:(RxMetadataStatus)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation ProvisioningEventTypeBox
- (instancetype)initWithValue:(ProvisioningEventType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface MeshNetwork ()
+ (MeshNetwork *)fromList:(NSArray<id> *)list;
+ (nullable MeshNetwork *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface NetworkKey ()
+ (NetworkKey *)fromList:(NSArray<id> *)list;
+ (nullable NetworkKey *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface AppKey ()
+ (AppKey *)fromList:(NSArray<id> *)list;
+ (nullable AppKey *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Provisioner ()
+ (Provisioner *)fromList:(NSArray<id> *)list;
+ (nullable Provisioner *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FlutterUnprovisionedDevice ()
+ (FlutterUnprovisionedDevice *)fromList:(NSArray<id> *)list;
+ (nullable FlutterUnprovisionedDevice *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ProvisionedNode ()
+ (ProvisionedNode *)fromList:(NSArray<id> *)list;
+ (nullable ProvisionedNode *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Element ()
+ (Element *)fromList:(NSArray<id> *)list;
+ (nullable Element *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Model ()
+ (Model *)fromList:(NSArray<id> *)list;
+ (nullable Model *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Publication ()
+ (Publication *)fromList:(NSArray<id> *)list;
+ (nullable Publication *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MeshGroup ()
+ (MeshGroup *)fromList:(NSArray<id> *)list;
+ (nullable MeshGroup *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MeshMessage ()
+ (MeshMessage *)fromList:(NSArray<id> *)list;
+ (nullable MeshMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface RxAccessMessage ()
+ (RxAccessMessage *)fromList:(NSArray<id> *)list;
+ (nullable RxAccessMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ProvisioningParameters ()
+ (ProvisioningParameters *)fromList:(NSArray<id> *)list;
+ (nullable ProvisioningParameters *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ProvisioningEvent ()
+ (ProvisioningEvent *)fromList:(NSArray<id> *)list;
+ (nullable ProvisioningEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface GenericOnOffSet ()
+ (GenericOnOffSet *)fromList:(NSArray<id> *)list;
+ (nullable GenericOnOffSet *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface GenericLevelSet ()
+ (GenericLevelSet *)fromList:(NSArray<id> *)list;
+ (nullable GenericLevelSet *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation MeshNetwork
+ (instancetype)makeWithNetworkId:(nullable NSString *)networkId
    name:(nullable NSString *)name
    networkKeys:(nullable NSArray<NetworkKey *> *)networkKeys
    appKeys:(nullable NSArray<AppKey *> *)appKeys
    nodes:(nullable NSArray<ProvisionedNode *> *)nodes
    groups:(nullable NSArray<MeshGroup *> *)groups
    provisioner:(nullable Provisioner *)provisioner {
  MeshNetwork* pigeonResult = [[MeshNetwork alloc] init];
  pigeonResult.networkId = networkId;
  pigeonResult.name = name;
  pigeonResult.networkKeys = networkKeys;
  pigeonResult.appKeys = appKeys;
  pigeonResult.nodes = nodes;
  pigeonResult.groups = groups;
  pigeonResult.provisioner = provisioner;
  return pigeonResult;
}
+ (MeshNetwork *)fromList:(NSArray<id> *)list {
  MeshNetwork *pigeonResult = [[MeshNetwork alloc] init];
  pigeonResult.networkId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.networkKeys = GetNullableObjectAtIndex(list, 2);
  pigeonResult.appKeys = GetNullableObjectAtIndex(list, 3);
  pigeonResult.nodes = GetNullableObjectAtIndex(list, 4);
  pigeonResult.groups = GetNullableObjectAtIndex(list, 5);
  pigeonResult.provisioner = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable MeshNetwork *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MeshNetwork fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.networkId ?: [NSNull null],
    self.name ?: [NSNull null],
    self.networkKeys ?: [NSNull null],
    self.appKeys ?: [NSNull null],
    self.nodes ?: [NSNull null],
    self.groups ?: [NSNull null],
    self.provisioner ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  MeshNetwork *other = (MeshNetwork *)object;
  return FLTPigeonDeepEquals(self.networkId, other.networkId) && FLTPigeonDeepEquals(self.name, other.name) && FLTPigeonDeepEquals(self.networkKeys, other.networkKeys) && FLTPigeonDeepEquals(self.appKeys, other.appKeys) && FLTPigeonDeepEquals(self.nodes, other.nodes) && FLTPigeonDeepEquals(self.groups, other.groups) && FLTPigeonDeepEquals(self.provisioner, other.provisioner);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.networkId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + FLTPigeonDeepHash(self.networkKeys);
  result = result * 31 + FLTPigeonDeepHash(self.appKeys);
  result = result * 31 + FLTPigeonDeepHash(self.nodes);
  result = result * 31 + FLTPigeonDeepHash(self.groups);
  result = result * 31 + FLTPigeonDeepHash(self.provisioner);
  return result;
}
@end

@implementation NetworkKey
+ (instancetype)makeWithKeyId:(nullable NSString *)keyId
    key:(nullable NSString *)key
    index:(nullable NSNumber *)index
    enabled:(nullable NSNumber *)enabled {
  NetworkKey* pigeonResult = [[NetworkKey alloc] init];
  pigeonResult.keyId = keyId;
  pigeonResult.key = key;
  pigeonResult.index = index;
  pigeonResult.enabled = enabled;
  return pigeonResult;
}
+ (NetworkKey *)fromList:(NSArray<id> *)list {
  NetworkKey *pigeonResult = [[NetworkKey alloc] init];
  pigeonResult.keyId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.key = GetNullableObjectAtIndex(list, 1);
  pigeonResult.index = GetNullableObjectAtIndex(list, 2);
  pigeonResult.enabled = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable NetworkKey *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [NetworkKey fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.keyId ?: [NSNull null],
    self.key ?: [NSNull null],
    self.index ?: [NSNull null],
    self.enabled ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  NetworkKey *other = (NetworkKey *)object;
  return FLTPigeonDeepEquals(self.keyId, other.keyId) && FLTPigeonDeepEquals(self.key, other.key) && FLTPigeonDeepEquals(self.index, other.index) && FLTPigeonDeepEquals(self.enabled, other.enabled);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.keyId);
  result = result * 31 + FLTPigeonDeepHash(self.key);
  result = result * 31 + FLTPigeonDeepHash(self.index);
  result = result * 31 + FLTPigeonDeepHash(self.enabled);
  return result;
}
@end

@implementation AppKey
+ (instancetype)makeWithKeyId:(nullable NSString *)keyId
    key:(nullable NSString *)key
    index:(nullable NSNumber *)index
    enabled:(nullable NSNumber *)enabled {
  AppKey* pigeonResult = [[AppKey alloc] init];
  pigeonResult.keyId = keyId;
  pigeonResult.key = key;
  pigeonResult.index = index;
  pigeonResult.enabled = enabled;
  return pigeonResult;
}
+ (AppKey *)fromList:(NSArray<id> *)list {
  AppKey *pigeonResult = [[AppKey alloc] init];
  pigeonResult.keyId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.key = GetNullableObjectAtIndex(list, 1);
  pigeonResult.index = GetNullableObjectAtIndex(list, 2);
  pigeonResult.enabled = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable AppKey *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [AppKey fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.keyId ?: [NSNull null],
    self.key ?: [NSNull null],
    self.index ?: [NSNull null],
    self.enabled ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  AppKey *other = (AppKey *)object;
  return FLTPigeonDeepEquals(self.keyId, other.keyId) && FLTPigeonDeepEquals(self.key, other.key) && FLTPigeonDeepEquals(self.index, other.index) && FLTPigeonDeepEquals(self.enabled, other.enabled);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.keyId);
  result = result * 31 + FLTPigeonDeepHash(self.key);
  result = result * 31 + FLTPigeonDeepHash(self.index);
  result = result * 31 + FLTPigeonDeepHash(self.enabled);
  return result;
}
@end

@implementation Provisioner
+ (instancetype)makeWithName:(nullable NSString *)name
    provisionerId:(nullable NSString *)provisionerId
    addressRange:(nullable NSArray<NSNumber *> *)addressRange {
  Provisioner* pigeonResult = [[Provisioner alloc] init];
  pigeonResult.name = name;
  pigeonResult.provisionerId = provisionerId;
  pigeonResult.addressRange = addressRange;
  return pigeonResult;
}
+ (Provisioner *)fromList:(NSArray<id> *)list {
  Provisioner *pigeonResult = [[Provisioner alloc] init];
  pigeonResult.name = GetNullableObjectAtIndex(list, 0);
  pigeonResult.provisionerId = GetNullableObjectAtIndex(list, 1);
  pigeonResult.addressRange = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable Provisioner *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Provisioner fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.name ?: [NSNull null],
    self.provisionerId ?: [NSNull null],
    self.addressRange ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  Provisioner *other = (Provisioner *)object;
  return FLTPigeonDeepEquals(self.name, other.name) && FLTPigeonDeepEquals(self.provisionerId, other.provisionerId) && FLTPigeonDeepEquals(self.addressRange, other.addressRange);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + FLTPigeonDeepHash(self.provisionerId);
  result = result * 31 + FLTPigeonDeepHash(self.addressRange);
  return result;
}
@end

@implementation FlutterUnprovisionedDevice
+ (instancetype)makeWithDeviceId:(nullable NSString *)deviceId
    name:(nullable NSString *)name
    rssi:(nullable NSNumber *)rssi
    uuid:(nullable NSArray<NSNumber *> *)uuid
    serviceUuid:(nullable NSString *)serviceUuid {
  FlutterUnprovisionedDevice* pigeonResult = [[FlutterUnprovisionedDevice alloc] init];
  pigeonResult.deviceId = deviceId;
  pigeonResult.name = name;
  pigeonResult.rssi = rssi;
  pigeonResult.uuid = uuid;
  pigeonResult.serviceUuid = serviceUuid;
  return pigeonResult;
}
+ (FlutterUnprovisionedDevice *)fromList:(NSArray<id> *)list {
  FlutterUnprovisionedDevice *pigeonResult = [[FlutterUnprovisionedDevice alloc] init];
  pigeonResult.deviceId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.rssi = GetNullableObjectAtIndex(list, 2);
  pigeonResult.uuid = GetNullableObjectAtIndex(list, 3);
  pigeonResult.serviceUuid = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable FlutterUnprovisionedDevice *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FlutterUnprovisionedDevice fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.deviceId ?: [NSNull null],
    self.name ?: [NSNull null],
    self.rssi ?: [NSNull null],
    self.uuid ?: [NSNull null],
    self.serviceUuid ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  FlutterUnprovisionedDevice *other = (FlutterUnprovisionedDevice *)object;
  return FLTPigeonDeepEquals(self.deviceId, other.deviceId) && FLTPigeonDeepEquals(self.name, other.name) && FLTPigeonDeepEquals(self.rssi, other.rssi) && FLTPigeonDeepEquals(self.uuid, other.uuid) && FLTPigeonDeepEquals(self.serviceUuid, other.serviceUuid);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.deviceId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + FLTPigeonDeepHash(self.rssi);
  result = result * 31 + FLTPigeonDeepHash(self.uuid);
  result = result * 31 + FLTPigeonDeepHash(self.serviceUuid);
  return result;
}
@end

@implementation ProvisionedNode
+ (instancetype)makeWithNodeId:(nullable NSString *)nodeId
    name:(nullable NSString *)name
    unicastAddress:(nullable NSNumber *)unicastAddress
    uuid:(nullable NSArray<NSNumber *> *)uuid
    elements:(nullable NSArray<Element *> *)elements
    provisioned:(nullable NSNumber *)provisioned {
  ProvisionedNode* pigeonResult = [[ProvisionedNode alloc] init];
  pigeonResult.nodeId = nodeId;
  pigeonResult.name = name;
  pigeonResult.unicastAddress = unicastAddress;
  pigeonResult.uuid = uuid;
  pigeonResult.elements = elements;
  pigeonResult.provisioned = provisioned;
  return pigeonResult;
}
+ (ProvisionedNode *)fromList:(NSArray<id> *)list {
  ProvisionedNode *pigeonResult = [[ProvisionedNode alloc] init];
  pigeonResult.nodeId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.unicastAddress = GetNullableObjectAtIndex(list, 2);
  pigeonResult.uuid = GetNullableObjectAtIndex(list, 3);
  pigeonResult.elements = GetNullableObjectAtIndex(list, 4);
  pigeonResult.provisioned = GetNullableObjectAtIndex(list, 5);
  return pigeonResult;
}
+ (nullable ProvisionedNode *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ProvisionedNode fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.nodeId ?: [NSNull null],
    self.name ?: [NSNull null],
    self.unicastAddress ?: [NSNull null],
    self.uuid ?: [NSNull null],
    self.elements ?: [NSNull null],
    self.provisioned ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  ProvisionedNode *other = (ProvisionedNode *)object;
  return FLTPigeonDeepEquals(self.nodeId, other.nodeId) && FLTPigeonDeepEquals(self.name, other.name) && FLTPigeonDeepEquals(self.unicastAddress, other.unicastAddress) && FLTPigeonDeepEquals(self.uuid, other.uuid) && FLTPigeonDeepEquals(self.elements, other.elements) && FLTPigeonDeepEquals(self.provisioned, other.provisioned);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.nodeId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + FLTPigeonDeepHash(self.unicastAddress);
  result = result * 31 + FLTPigeonDeepHash(self.uuid);
  result = result * 31 + FLTPigeonDeepHash(self.elements);
  result = result * 31 + FLTPigeonDeepHash(self.provisioned);
  return result;
}
@end

@implementation Element
+ (instancetype)makeWithAddress:(nullable NSNumber *)address
    models:(nullable NSArray<Model *> *)models {
  Element* pigeonResult = [[Element alloc] init];
  pigeonResult.address = address;
  pigeonResult.models = models;
  return pigeonResult;
}
+ (Element *)fromList:(NSArray<id> *)list {
  Element *pigeonResult = [[Element alloc] init];
  pigeonResult.address = GetNullableObjectAtIndex(list, 0);
  pigeonResult.models = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable Element *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Element fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.address ?: [NSNull null],
    self.models ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  Element *other = (Element *)object;
  return FLTPigeonDeepEquals(self.address, other.address) && FLTPigeonDeepEquals(self.models, other.models);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.address);
  result = result * 31 + FLTPigeonDeepHash(self.models);
  return result;
}
@end

@implementation Model
+ (instancetype)makeWithModelId:(nullable NSNumber *)modelId
    modelName:(nullable NSString *)modelName
    publishable:(nullable NSNumber *)publishable
    subscribable:(nullable NSNumber *)subscribable
    boundAppKeyIndexes:(nullable NSArray<NSNumber *> *)boundAppKeyIndexes
    subscriptions:(nullable NSArray<NSNumber *> *)subscriptions
    publication:(nullable Publication *)publication {
  Model* pigeonResult = [[Model alloc] init];
  pigeonResult.modelId = modelId;
  pigeonResult.modelName = modelName;
  pigeonResult.publishable = publishable;
  pigeonResult.subscribable = subscribable;
  pigeonResult.boundAppKeyIndexes = boundAppKeyIndexes;
  pigeonResult.subscriptions = subscriptions;
  pigeonResult.publication = publication;
  return pigeonResult;
}
+ (Model *)fromList:(NSArray<id> *)list {
  Model *pigeonResult = [[Model alloc] init];
  pigeonResult.modelId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.modelName = GetNullableObjectAtIndex(list, 1);
  pigeonResult.publishable = GetNullableObjectAtIndex(list, 2);
  pigeonResult.subscribable = GetNullableObjectAtIndex(list, 3);
  pigeonResult.boundAppKeyIndexes = GetNullableObjectAtIndex(list, 4);
  pigeonResult.subscriptions = GetNullableObjectAtIndex(list, 5);
  pigeonResult.publication = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable Model *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Model fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.modelId ?: [NSNull null],
    self.modelName ?: [NSNull null],
    self.publishable ?: [NSNull null],
    self.subscribable ?: [NSNull null],
    self.boundAppKeyIndexes ?: [NSNull null],
    self.subscriptions ?: [NSNull null],
    self.publication ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  Model *other = (Model *)object;
  return FLTPigeonDeepEquals(self.modelId, other.modelId) && FLTPigeonDeepEquals(self.modelName, other.modelName) && FLTPigeonDeepEquals(self.publishable, other.publishable) && FLTPigeonDeepEquals(self.subscribable, other.subscribable) && FLTPigeonDeepEquals(self.boundAppKeyIndexes, other.boundAppKeyIndexes) && FLTPigeonDeepEquals(self.subscriptions, other.subscriptions) && FLTPigeonDeepEquals(self.publication, other.publication);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.modelId);
  result = result * 31 + FLTPigeonDeepHash(self.modelName);
  result = result * 31 + FLTPigeonDeepHash(self.publishable);
  result = result * 31 + FLTPigeonDeepHash(self.subscribable);
  result = result * 31 + FLTPigeonDeepHash(self.boundAppKeyIndexes);
  result = result * 31 + FLTPigeonDeepHash(self.subscriptions);
  result = result * 31 + FLTPigeonDeepHash(self.publication);
  return result;
}
@end

@implementation Publication
+ (instancetype)makeWithAddress:(nullable NSNumber *)address
    appKeyIndex:(nullable NSNumber *)appKeyIndex
    ttl:(nullable NSNumber *)ttl {
  Publication* pigeonResult = [[Publication alloc] init];
  pigeonResult.address = address;
  pigeonResult.appKeyIndex = appKeyIndex;
  pigeonResult.ttl = ttl;
  return pigeonResult;
}
+ (Publication *)fromList:(NSArray<id> *)list {
  Publication *pigeonResult = [[Publication alloc] init];
  pigeonResult.address = GetNullableObjectAtIndex(list, 0);
  pigeonResult.appKeyIndex = GetNullableObjectAtIndex(list, 1);
  pigeonResult.ttl = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable Publication *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Publication fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.address ?: [NSNull null],
    self.appKeyIndex ?: [NSNull null],
    self.ttl ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  Publication *other = (Publication *)object;
  return FLTPigeonDeepEquals(self.address, other.address) && FLTPigeonDeepEquals(self.appKeyIndex, other.appKeyIndex) && FLTPigeonDeepEquals(self.ttl, other.ttl);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.address);
  result = result * 31 + FLTPigeonDeepHash(self.appKeyIndex);
  result = result * 31 + FLTPigeonDeepHash(self.ttl);
  return result;
}
@end

@implementation MeshGroup
+ (instancetype)makeWithGroupId:(nullable NSString *)groupId
    name:(nullable NSString *)name
    address:(nullable NSNumber *)address
    nodeIds:(nullable NSArray<NSString *> *)nodeIds {
  MeshGroup* pigeonResult = [[MeshGroup alloc] init];
  pigeonResult.groupId = groupId;
  pigeonResult.name = name;
  pigeonResult.address = address;
  pigeonResult.nodeIds = nodeIds;
  return pigeonResult;
}
+ (MeshGroup *)fromList:(NSArray<id> *)list {
  MeshGroup *pigeonResult = [[MeshGroup alloc] init];
  pigeonResult.groupId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.address = GetNullableObjectAtIndex(list, 2);
  pigeonResult.nodeIds = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable MeshGroup *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MeshGroup fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.groupId ?: [NSNull null],
    self.name ?: [NSNull null],
    self.address ?: [NSNull null],
    self.nodeIds ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  MeshGroup *other = (MeshGroup *)object;
  return FLTPigeonDeepEquals(self.groupId, other.groupId) && FLTPigeonDeepEquals(self.name, other.name) && FLTPigeonDeepEquals(self.address, other.address) && FLTPigeonDeepEquals(self.nodeIds, other.nodeIds);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.groupId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + FLTPigeonDeepHash(self.address);
  result = result * 31 + FLTPigeonDeepHash(self.nodeIds);
  return result;
}
@end

@implementation MeshMessage
+ (instancetype)makeWithOpcode:(nullable NSNumber *)opcode
    address:(nullable NSNumber *)address
    appKeyIndex:(nullable NSNumber *)appKeyIndex
    parameters:(nullable NSDictionary<NSString *, id> *)parameters {
  MeshMessage* pigeonResult = [[MeshMessage alloc] init];
  pigeonResult.opcode = opcode;
  pigeonResult.address = address;
  pigeonResult.appKeyIndex = appKeyIndex;
  pigeonResult.parameters = parameters;
  return pigeonResult;
}
+ (MeshMessage *)fromList:(NSArray<id> *)list {
  MeshMessage *pigeonResult = [[MeshMessage alloc] init];
  pigeonResult.opcode = GetNullableObjectAtIndex(list, 0);
  pigeonResult.address = GetNullableObjectAtIndex(list, 1);
  pigeonResult.appKeyIndex = GetNullableObjectAtIndex(list, 2);
  pigeonResult.parameters = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable MeshMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MeshMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.opcode ?: [NSNull null],
    self.address ?: [NSNull null],
    self.appKeyIndex ?: [NSNull null],
    self.parameters ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  MeshMessage *other = (MeshMessage *)object;
  return FLTPigeonDeepEquals(self.opcode, other.opcode) && FLTPigeonDeepEquals(self.address, other.address) && FLTPigeonDeepEquals(self.appKeyIndex, other.appKeyIndex) && FLTPigeonDeepEquals(self.parameters, other.parameters);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.opcode);
  result = result * 31 + FLTPigeonDeepHash(self.address);
  result = result * 31 + FLTPigeonDeepHash(self.appKeyIndex);
  result = result * 31 + FLTPigeonDeepHash(self.parameters);
  return result;
}
@end

@implementation RxAccessMessage
+ (instancetype)makeWithOpcode:(nullable NSNumber *)opcode
    parameters:(nullable NSArray<NSNumber *> *)parameters
    source:(nullable NSNumber *)source
    destination:(nullable NSNumber *)destination
    metadataStatus:(nullable RxMetadataStatusBox *)metadataStatus {
  RxAccessMessage* pigeonResult = [[RxAccessMessage alloc] init];
  pigeonResult.opcode = opcode;
  pigeonResult.parameters = parameters;
  pigeonResult.source = source;
  pigeonResult.destination = destination;
  pigeonResult.metadataStatus = metadataStatus;
  return pigeonResult;
}
+ (RxAccessMessage *)fromList:(NSArray<id> *)list {
  RxAccessMessage *pigeonResult = [[RxAccessMessage alloc] init];
  pigeonResult.opcode = GetNullableObjectAtIndex(list, 0);
  pigeonResult.parameters = GetNullableObjectAtIndex(list, 1);
  pigeonResult.source = GetNullableObjectAtIndex(list, 2);
  pigeonResult.destination = GetNullableObjectAtIndex(list, 3);
  pigeonResult.metadataStatus = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable RxAccessMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [RxAccessMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.opcode ?: [NSNull null],
    self.parameters ?: [NSNull null],
    self.source ?: [NSNull null],
    self.destination ?: [NSNull null],
    self.metadataStatus ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  RxAccessMessage *other = (RxAccessMessage *)object;
  return FLTPigeonDeepEquals(self.opcode, other.opcode) && FLTPigeonDeepEquals(self.parameters, other.parameters) && FLTPigeonDeepEquals(self.source, other.source) && FLTPigeonDeepEquals(self.destination, other.destination) && FLTPigeonDeepEquals(self.metadataStatus, other.metadataStatus);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.opcode);
  result = result * 31 + FLTPigeonDeepHash(self.parameters);
  result = result * 31 + FLTPigeonDeepHash(self.source);
  result = result * 31 + FLTPigeonDeepHash(self.destination);
  result = result * 31 + FLTPigeonDeepHash(self.metadataStatus);
  return result;
}
@end

@implementation ProvisioningParameters
+ (instancetype)makeWithDeviceName:(nullable NSString *)deviceName
    oobMethod:(nullable NSNumber *)oobMethod
    oobData:(nullable NSString *)oobData
    enablePrivacy:(nullable NSNumber *)enablePrivacy {
  ProvisioningParameters* pigeonResult = [[ProvisioningParameters alloc] init];
  pigeonResult.deviceName = deviceName;
  pigeonResult.oobMethod = oobMethod;
  pigeonResult.oobData = oobData;
  pigeonResult.enablePrivacy = enablePrivacy;
  return pigeonResult;
}
+ (ProvisioningParameters *)fromList:(NSArray<id> *)list {
  ProvisioningParameters *pigeonResult = [[ProvisioningParameters alloc] init];
  pigeonResult.deviceName = GetNullableObjectAtIndex(list, 0);
  pigeonResult.oobMethod = GetNullableObjectAtIndex(list, 1);
  pigeonResult.oobData = GetNullableObjectAtIndex(list, 2);
  pigeonResult.enablePrivacy = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable ProvisioningParameters *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ProvisioningParameters fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.deviceName ?: [NSNull null],
    self.oobMethod ?: [NSNull null],
    self.oobData ?: [NSNull null],
    self.enablePrivacy ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  ProvisioningParameters *other = (ProvisioningParameters *)object;
  return FLTPigeonDeepEquals(self.deviceName, other.deviceName) && FLTPigeonDeepEquals(self.oobMethod, other.oobMethod) && FLTPigeonDeepEquals(self.oobData, other.oobData) && FLTPigeonDeepEquals(self.enablePrivacy, other.enablePrivacy);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.deviceName);
  result = result * 31 + FLTPigeonDeepHash(self.oobMethod);
  result = result * 31 + FLTPigeonDeepHash(self.oobData);
  result = result * 31 + FLTPigeonDeepHash(self.enablePrivacy);
  return result;
}
@end

@implementation ProvisioningEvent
+ (instancetype)makeWithDeviceId:(nullable NSString *)deviceId
    type:(nullable ProvisioningEventTypeBox *)type
    message:(nullable NSString *)message
    progress:(nullable NSNumber *)progress
    attentionTimer:(nullable NSNumber *)attentionTimer {
  ProvisioningEvent* pigeonResult = [[ProvisioningEvent alloc] init];
  pigeonResult.deviceId = deviceId;
  pigeonResult.type = type;
  pigeonResult.message = message;
  pigeonResult.progress = progress;
  pigeonResult.attentionTimer = attentionTimer;
  return pigeonResult;
}
+ (ProvisioningEvent *)fromList:(NSArray<id> *)list {
  ProvisioningEvent *pigeonResult = [[ProvisioningEvent alloc] init];
  pigeonResult.deviceId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.type = GetNullableObjectAtIndex(list, 1);
  pigeonResult.message = GetNullableObjectAtIndex(list, 2);
  pigeonResult.progress = GetNullableObjectAtIndex(list, 3);
  pigeonResult.attentionTimer = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable ProvisioningEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ProvisioningEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.deviceId ?: [NSNull null],
    self.type ?: [NSNull null],
    self.message ?: [NSNull null],
    self.progress ?: [NSNull null],
    self.attentionTimer ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  ProvisioningEvent *other = (ProvisioningEvent *)object;
  return FLTPigeonDeepEquals(self.deviceId, other.deviceId) && FLTPigeonDeepEquals(self.type, other.type) && FLTPigeonDeepEquals(self.message, other.message) && FLTPigeonDeepEquals(self.progress, other.progress) && FLTPigeonDeepEquals(self.attentionTimer, other.attentionTimer);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.deviceId);
  result = result * 31 + FLTPigeonDeepHash(self.type);
  result = result * 31 + FLTPigeonDeepHash(self.message);
  result = result * 31 + FLTPigeonDeepHash(self.progress);
  result = result * 31 + FLTPigeonDeepHash(self.attentionTimer);
  return result;
}
@end

@implementation GenericOnOffSet
+ (instancetype)makeWithState:(nullable NSNumber *)state
    transitionTime:(nullable NSNumber *)transitionTime
    delay:(nullable NSNumber *)delay {
  GenericOnOffSet* pigeonResult = [[GenericOnOffSet alloc] init];
  pigeonResult.state = state;
  pigeonResult.transitionTime = transitionTime;
  pigeonResult.delay = delay;
  return pigeonResult;
}
+ (GenericOnOffSet *)fromList:(NSArray<id> *)list {
  GenericOnOffSet *pigeonResult = [[GenericOnOffSet alloc] init];
  pigeonResult.state = GetNullableObjectAtIndex(list, 0);
  pigeonResult.transitionTime = GetNullableObjectAtIndex(list, 1);
  pigeonResult.delay = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable GenericOnOffSet *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [GenericOnOffSet fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.state ?: [NSNull null],
    self.transitionTime ?: [NSNull null],
    self.delay ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  GenericOnOffSet *other = (GenericOnOffSet *)object;
  return FLTPigeonDeepEquals(self.state, other.state) && FLTPigeonDeepEquals(self.transitionTime, other.transitionTime) && FLTPigeonDeepEquals(self.delay, other.delay);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.state);
  result = result * 31 + FLTPigeonDeepHash(self.transitionTime);
  result = result * 31 + FLTPigeonDeepHash(self.delay);
  return result;
}
@end

@implementation GenericLevelSet
+ (instancetype)makeWithLevel:(nullable NSNumber *)level
    transitionTime:(nullable NSNumber *)transitionTime
    delay:(nullable NSNumber *)delay {
  GenericLevelSet* pigeonResult = [[GenericLevelSet alloc] init];
  pigeonResult.level = level;
  pigeonResult.transitionTime = transitionTime;
  pigeonResult.delay = delay;
  return pigeonResult;
}
+ (GenericLevelSet *)fromList:(NSArray<id> *)list {
  GenericLevelSet *pigeonResult = [[GenericLevelSet alloc] init];
  pigeonResult.level = GetNullableObjectAtIndex(list, 0);
  pigeonResult.transitionTime = GetNullableObjectAtIndex(list, 1);
  pigeonResult.delay = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable GenericLevelSet *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [GenericLevelSet fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.level ?: [NSNull null],
    self.transitionTime ?: [NSNull null],
    self.delay ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  GenericLevelSet *other = (GenericLevelSet *)object;
  return FLTPigeonDeepEquals(self.level, other.level) && FLTPigeonDeepEquals(self.transitionTime, other.transitionTime) && FLTPigeonDeepEquals(self.delay, other.delay);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.level);
  result = result * 31 + FLTPigeonDeepHash(self.transitionTime);
  result = result * 31 + FLTPigeonDeepHash(self.delay);
  return result;
}
@end

@interface nullPigeonGeneratedPigeonCodecReader : FlutterStandardReader
@end
@implementation nullPigeonGeneratedPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[RxMetadataStatusBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[ProvisioningEventTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: 
      return [MeshNetwork fromList:[self readValue]];
    case 132: 
      return [NetworkKey fromList:[self readValue]];
    case 133: 
      return [AppKey fromList:[self readValue]];
    case 134: 
      return [Provisioner fromList:[self readValue]];
    case 135: 
      return [FlutterUnprovisionedDevice fromList:[self readValue]];
    case 136: 
      return [ProvisionedNode fromList:[self readValue]];
    case 137: 
      return [Element fromList:[self readValue]];
    case 138: 
      return [Model fromList:[self readValue]];
    case 139: 
      return [Publication fromList:[self readValue]];
    case 140: 
      return [MeshGroup fromList:[self readValue]];
    case 141: 
      return [MeshMessage fromList:[self readValue]];
    case 142: 
      return [RxAccessMessage fromList:[self readValue]];
    case 143: 
      return [ProvisioningParameters fromList:[self readValue]];
    case 144: 
      return [ProvisioningEvent fromList:[self readValue]];
    case 145: 
      return [GenericOnOffSet fromList:[self readValue]];
    case 146: 
      return [GenericLevelSet fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullPigeonGeneratedPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullPigeonGeneratedPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[RxMetadataStatusBox class]]) {
    RxMetadataStatusBox *box = (RxMetadataStatusBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[ProvisioningEventTypeBox class]]) {
    ProvisioningEventTypeBox *box = (ProvisioningEventTypeBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[MeshNetwork class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[NetworkKey class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[AppKey class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Provisioner class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FlutterUnprovisionedDevice class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ProvisionedNode class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Element class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Model class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Publication class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MeshGroup class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MeshMessage class]]) {
    [self writeByte:141];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[RxAccessMessage class]]) {
    [self writeByte:142];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ProvisioningParameters class]]) {
    [self writeByte:143];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ProvisioningEvent class]]) {
    [self writeByte:144];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[GenericOnOffSet class]]) {
    [self writeByte:145];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[GenericLevelSet class]]) {
    [self writeByte:146];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullPigeonGeneratedPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullPigeonGeneratedPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullPigeonGeneratedPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullPigeonGeneratedPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetPigeonGeneratedCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullPigeonGeneratedPigeonCodecReaderWriter *readerWriter = [[nullPigeonGeneratedPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpMeshApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MeshApi> *api) {
  SetUpMeshApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpMeshApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MeshApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createNetworkName:error:)], @"MeshApi api (%@) doesn't respond to @selector(createNetworkName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_name = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        MeshNetwork *output = [api createNetworkName:arg_name error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.loadNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(loadNetworkWithError:)], @"MeshApi api (%@) doesn't respond to @selector(loadNetworkWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        MeshNetwork *output = [api loadNetworkWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.saveNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(saveNetworkWithError:)], @"MeshApi api (%@) doesn't respond to @selector(saveNetworkWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api saveNetworkWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.exportNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(exportNetworkPath:error:)], @"MeshApi api (%@) doesn't respond to @selector(exportNetworkPath:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_path = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api exportNetworkPath:arg_path error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.importNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(importNetworkPath:error:)], @"MeshApi api (%@) doesn't respond to @selector(importNetworkPath:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_path = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api importNetworkPath:arg_path error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.startScan", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startScanWithError:)], @"MeshApi api (%@) doesn't respond to @selector(startScanWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api startScanWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.stopScan", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopScanWithError:)], @"MeshApi api (%@) doesn't respond to @selector(stopScanWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopScanWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provisionDevice", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(provisionDeviceDevice:params:error:)], @"MeshApi api (%@) doesn't respond to @selector(provisionDeviceDevice:params:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FlutterUnprovisionedDevice *arg_device = GetNullableObjectAtIndex(args, 0);
        ProvisioningParameters *arg_params = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        ProvisionedNode *output = [api provisionDeviceDevice:arg_device params:arg_params error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Provide user input required by Output OOB (numeric).
  ///
  /// Used when provisioning emits an OOB input request that requires the user to enter a value
  /// shown on the device.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provideProvisioningOobNumeric", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(provideProvisioningOobNumericDeviceId:value:error:)], @"MeshApi api (%@) doesn't respond to @selector(provideProvisioningOobNumericDeviceId:value:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_deviceId = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_value = [GetNullableObjectAtIndex(args, 1) integerValue];
        FlutterError *error;
        NSNumber *output = [api provideProvisioningOobNumericDeviceId:arg_deviceId value:arg_value error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Provide user input required by Output OOB (alphanumeric).
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provideProvisioningOobAlphaNumeric", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(provideProvisioningOobAlphaNumericDeviceId:value:error:)], @"MeshApi api (%@) doesn't respond to @selector(provideProvisioningOobAlphaNumericDeviceId:value:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_deviceId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_value = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        NSNumber *output = [api provideProvisioningOobAlphaNumericDeviceId:arg_deviceId value:arg_value error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.sendMessage", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendMessageMessage:error:)], @"MeshApi api (%@) doesn't respond to @selector(sendMessageMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        MeshMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api sendMessageMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getNodes", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getNodesWithError:)], @"MeshApi api (%@) doesn't respond to @selector(getNodesWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<ProvisionedNode *> *output = [api getNodesWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeNode", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(removeNodeNodeId:error:)], @"MeshApi api (%@) doesn't respond to @selector(removeNodeNodeId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_nodeId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api removeNodeNodeId:arg_nodeId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createGroup", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createGroupName:error:)], @"MeshApi api (%@) doesn't respond to @selector(createGroupName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_name = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        MeshGroup *output = [api createGroupName:arg_name error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getGroups", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getGroupsWithError:)], @"MeshApi api (%@) doesn't respond to @selector(getGroupsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<MeshGroup *> *output = [api getGroupsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addNodeToGroup", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(addNodeToGroupNodeId:groupId:error:)], @"MeshApi api (%@) doesn't respond to @selector(addNodeToGroupNodeId:groupId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_nodeId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_groupId = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api addNodeToGroupNodeId:arg_nodeId groupId:arg_groupId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Bind an AppKey to a model on a given element address.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.bindAppKey", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(bindAppKeyElementAddress:modelId:appKeyIndex:error:)], @"MeshApi api (%@) doesn't respond to @selector(bindAppKeyElementAddress:modelId:appKeyIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_elementAddress = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_modelId = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSInteger arg_appKeyIndex = [GetNullableObjectAtIndex(args, 2) integerValue];
        FlutterError *error;
        NSNumber *output = [api bindAppKeyElementAddress:arg_elementAddress modelId:arg_modelId appKeyIndex:arg_appKeyIndex error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Unbind an AppKey from a model on a given element address.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.unbindAppKey", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(unbindAppKeyElementAddress:modelId:appKeyIndex:error:)], @"MeshApi api (%@) doesn't respond to @selector(unbindAppKeyElementAddress:modelId:appKeyIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_elementAddress = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_modelId = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSInteger arg_appKeyIndex = [GetNullableObjectAtIndex(args, 2) integerValue];
        FlutterError *error;
        NSNumber *output = [api unbindAppKeyElementAddress:arg_elementAddress modelId:arg_modelId appKeyIndex:arg_appKeyIndex error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Add a subscription address to a model on a given element address.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addSubscription", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(addSubscriptionElementAddress:modelId:address:error:)], @"MeshApi api (%@) doesn't respond to @selector(addSubscriptionElementAddress:modelId:address:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_elementAddress = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_modelId = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSInteger arg_address = [GetNullableObjectAtIndex(args, 2) integerValue];
        FlutterError *error;
        NSNumber *output = [api addSubscriptionElementAddress:arg_elementAddress modelId:arg_modelId address:arg_address error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Remove a subscription address from a model on a given element address.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeSubscription", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(removeSubscriptionElementAddress:modelId:address:error:)], @"MeshApi api (%@) doesn't respond to @selector(removeSubscriptionElementAddress:modelId:address:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_elementAddress = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_modelId = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSInteger arg_address = [GetNullableObjectAtIndex(args, 2) integerValue];
        FlutterError *error;
        NSNumber *output = [api removeSubscriptionElementAddress:arg_elementAddress modelId:arg_modelId address:arg_address error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Set publication for a model on a given element address.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setPublication", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPublicationElementAddress:modelId:publishAddress:appKeyIndex:ttl:error:)], @"MeshApi api (%@) doesn't respond to @selector(setPublicationElementAddress:modelId:publishAddress:appKeyIndex:ttl:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_elementAddress = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_modelId = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSInteger arg_publishAddress = [GetNullableObjectAtIndex(args, 2) integerValue];
        NSInteger arg_appKeyIndex = [GetNullableObjectAtIndex(args, 3) integerValue];
        NSNumber *arg_ttl = GetNullableObjectAtIndex(args, 4);
        FlutterError *error;
        NSNumber *output = [api setPublicationElementAddress:arg_elementAddress modelId:arg_modelId publishAddress:arg_publishAddress appKeyIndex:arg_appKeyIndex ttl:arg_ttl error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.connectProxy", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(connectProxyDeviceId:proxyUnicastAddress:error:)], @"MeshApi api (%@) doesn't respond to @selector(connectProxyDeviceId:proxyUnicastAddress:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_deviceId = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_proxyUnicastAddress = [GetNullableObjectAtIndex(args, 1) integerValue];
        FlutterError *error;
        NSNumber *output = [api connectProxyDeviceId:arg_deviceId proxyUnicastAddress:arg_proxyUnicastAddress error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.disconnectProxy", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disconnectProxyWithError:)], @"MeshApi api (%@) doesn't respond to @selector(disconnectProxyWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api disconnectProxyWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.isProxyConnected", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isProxyConnectedWithError:)], @"MeshApi api (%@) doesn't respond to @selector(isProxyConnectedWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isProxyConnectedWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.connectProvisioning", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(connectProvisioningDeviceId:error:)], @"MeshApi api (%@) doesn't respond to @selector(connectProvisioningDeviceId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_deviceId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api connectProvisioningDeviceId:arg_deviceId error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.disconnectProvisioning", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disconnectProvisioningWithError:)], @"MeshApi api (%@) doesn't respond to @selector(disconnectProvisioningWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api disconnectProvisioningWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.isProvisioningConnected", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isProvisioningConnectedWithError:)], @"MeshApi api (%@) doesn't respond to @selector(isProvisioningConnectedWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isProvisioningConnectedWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Whether the native implementation can reliably populate `MeshMessage.address`
  /// (source address) for incoming Access messages.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.supportsRxSourceAddress", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(supportsRxSourceAddressWithError:)], @"MeshApi api (%@) doesn't respond to @selector(supportsRxSourceAddressWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api supportsRxSourceAddressWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Clear persisted secure mesh state used for stable Access message sending.
  ///
  /// Intended for debugging and recovery (e.g. when switching Mesh DBs).
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.clearSecureStorage", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(clearSecureStorageWithError:)], @"MeshApi api (%@) doesn't respond to @selector(clearSecureStorageWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api clearSecureStorageWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Enable/disable experimental RX metadata extraction on Android.
  ///
  /// When enabled, Android may use internal APIs (via reflection) to extract the
  /// source address for incoming Access messages. When disabled, Android will
  /// use only public APIs and `MeshMessage.address` may be null.
  ///
  /// On iOS this is a no-op.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setExperimentalRxMetadataEnabled", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setExperimentalRxMetadataEnabledEnabled:error:)], @"MeshApi api (%@) doesn't respond to @selector(setExperimentalRxMetadataEnabledEnabled:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_enabled = [GetNullableObjectAtIndex(args, 0) boolValue];
        FlutterError *error;
        [api setExperimentalRxMetadataEnabledEnabled:arg_enabled error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface MeshFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation MeshFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onDeviceDiscoveredDevice:(FlutterUnprovisionedDevice *)arg_device completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onDeviceDiscovered", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonGeneratedCodec()];
  [channel sendMessage:@[arg_device ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onMessageReceivedMessage:(MeshMessage *)arg_message completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onMessageReceived", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonGeneratedCodec()];
  [channel sendMessage:@[arg_message ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onRxAccessMessageEvent:(RxAccessMessage *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onRxAccessMessage", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonGeneratedCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onProvisioningEventEvent:(ProvisioningEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onProvisioningEvent", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonGeneratedCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

