// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "PigeonGenerated.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface MeshNetwork ()
+ (MeshNetwork *)fromList:(NSArray<id> *)list;
+ (nullable MeshNetwork *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface NetworkKey ()
+ (NetworkKey *)fromList:(NSArray<id> *)list;
+ (nullable NetworkKey *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface AppKey ()
+ (AppKey *)fromList:(NSArray<id> *)list;
+ (nullable AppKey *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Provisioner ()
+ (Provisioner *)fromList:(NSArray<id> *)list;
+ (nullable Provisioner *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface UnprovisionedDevice ()
+ (UnprovisionedDevice *)fromList:(NSArray<id> *)list;
+ (nullable UnprovisionedDevice *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ProvisionedNode ()
+ (ProvisionedNode *)fromList:(NSArray<id> *)list;
+ (nullable ProvisionedNode *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Element ()
+ (Element *)fromList:(NSArray<id> *)list;
+ (nullable Element *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Model ()
+ (Model *)fromList:(NSArray<id> *)list;
+ (nullable Model *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MeshGroup ()
+ (MeshGroup *)fromList:(NSArray<id> *)list;
+ (nullable MeshGroup *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MeshMessage ()
+ (MeshMessage *)fromList:(NSArray<id> *)list;
+ (nullable MeshMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ProvisioningParameters ()
+ (ProvisioningParameters *)fromList:(NSArray<id> *)list;
+ (nullable ProvisioningParameters *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface GenericOnOffSet ()
+ (GenericOnOffSet *)fromList:(NSArray<id> *)list;
+ (nullable GenericOnOffSet *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface GenericLevelSet ()
+ (GenericLevelSet *)fromList:(NSArray<id> *)list;
+ (nullable GenericLevelSet *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation MeshNetwork
+ (instancetype)makeWithNetworkId:(NSString *)networkId
    name:(NSString *)name
    networkKeys:(NSArray<NetworkKey *> *)networkKeys
    appKeys:(NSArray<AppKey *> *)appKeys
    nodes:(NSArray<ProvisionedNode *> *)nodes
    groups:(NSArray<MeshGroup *> *)groups
    provisioner:(Provisioner *)provisioner {
  MeshNetwork* pigeonResult = [[MeshNetwork alloc] init];
  pigeonResult.networkId = networkId;
  pigeonResult.name = name;
  pigeonResult.networkKeys = networkKeys;
  pigeonResult.appKeys = appKeys;
  pigeonResult.nodes = nodes;
  pigeonResult.groups = groups;
  pigeonResult.provisioner = provisioner;
  return pigeonResult;
}
+ (MeshNetwork *)fromList:(NSArray<id> *)list {
  MeshNetwork *pigeonResult = [[MeshNetwork alloc] init];
  pigeonResult.networkId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.networkKeys = GetNullableObjectAtIndex(list, 2);
  pigeonResult.appKeys = GetNullableObjectAtIndex(list, 3);
  pigeonResult.nodes = GetNullableObjectAtIndex(list, 4);
  pigeonResult.groups = GetNullableObjectAtIndex(list, 5);
  pigeonResult.provisioner = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable MeshNetwork *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MeshNetwork fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.networkId ?: [NSNull null],
    self.name ?: [NSNull null],
    self.networkKeys ?: [NSNull null],
    self.appKeys ?: [NSNull null],
    self.nodes ?: [NSNull null],
    self.groups ?: [NSNull null],
    self.provisioner ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  MeshNetwork *other = (MeshNetwork *)object;
  return FLTPigeonDeepEquals(self.networkId, other.networkId) && FLTPigeonDeepEquals(self.name, other.name) && FLTPigeonDeepEquals(self.networkKeys, other.networkKeys) && FLTPigeonDeepEquals(self.appKeys, other.appKeys) && FLTPigeonDeepEquals(self.nodes, other.nodes) && FLTPigeonDeepEquals(self.groups, other.groups) && FLTPigeonDeepEquals(self.provisioner, other.provisioner);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.networkId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + FLTPigeonDeepHash(self.networkKeys);
  result = result * 31 + FLTPigeonDeepHash(self.appKeys);
  result = result * 31 + FLTPigeonDeepHash(self.nodes);
  result = result * 31 + FLTPigeonDeepHash(self.groups);
  result = result * 31 + FLTPigeonDeepHash(self.provisioner);
  return result;
}
@end

@implementation NetworkKey
+ (instancetype)makeWithKeyId:(NSString *)keyId
    key:(NSString *)key
    index:(NSInteger )index
    enabled:(BOOL )enabled {
  NetworkKey* pigeonResult = [[NetworkKey alloc] init];
  pigeonResult.keyId = keyId;
  pigeonResult.key = key;
  pigeonResult.index = index;
  pigeonResult.enabled = enabled;
  return pigeonResult;
}
+ (NetworkKey *)fromList:(NSArray<id> *)list {
  NetworkKey *pigeonResult = [[NetworkKey alloc] init];
  pigeonResult.keyId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.key = GetNullableObjectAtIndex(list, 1);
  pigeonResult.index = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.enabled = [GetNullableObjectAtIndex(list, 3) boolValue];
  return pigeonResult;
}
+ (nullable NetworkKey *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [NetworkKey fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.keyId ?: [NSNull null],
    self.key ?: [NSNull null],
    @(self.index),
    @(self.enabled),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  NetworkKey *other = (NetworkKey *)object;
  return FLTPigeonDeepEquals(self.keyId, other.keyId) && FLTPigeonDeepEquals(self.key, other.key) && self.index == other.index && self.enabled == other.enabled;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.keyId);
  result = result * 31 + FLTPigeonDeepHash(self.key);
  result = result * 31 + @(self.index).hash;
  result = result * 31 + @(self.enabled).hash;
  return result;
}
@end

@implementation AppKey
+ (instancetype)makeWithKeyId:(NSString *)keyId
    key:(NSString *)key
    index:(NSInteger )index
    enabled:(BOOL )enabled {
  AppKey* pigeonResult = [[AppKey alloc] init];
  pigeonResult.keyId = keyId;
  pigeonResult.key = key;
  pigeonResult.index = index;
  pigeonResult.enabled = enabled;
  return pigeonResult;
}
+ (AppKey *)fromList:(NSArray<id> *)list {
  AppKey *pigeonResult = [[AppKey alloc] init];
  pigeonResult.keyId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.key = GetNullableObjectAtIndex(list, 1);
  pigeonResult.index = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.enabled = [GetNullableObjectAtIndex(list, 3) boolValue];
  return pigeonResult;
}
+ (nullable AppKey *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [AppKey fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.keyId ?: [NSNull null],
    self.key ?: [NSNull null],
    @(self.index),
    @(self.enabled),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  AppKey *other = (AppKey *)object;
  return FLTPigeonDeepEquals(self.keyId, other.keyId) && FLTPigeonDeepEquals(self.key, other.key) && self.index == other.index && self.enabled == other.enabled;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.keyId);
  result = result * 31 + FLTPigeonDeepHash(self.key);
  result = result * 31 + @(self.index).hash;
  result = result * 31 + @(self.enabled).hash;
  return result;
}
@end

@implementation Provisioner
+ (instancetype)makeWithName:(NSString *)name
    provisionerId:(NSString *)provisionerId
    addressRange:(NSArray<NSNumber *> *)addressRange {
  Provisioner* pigeonResult = [[Provisioner alloc] init];
  pigeonResult.name = name;
  pigeonResult.provisionerId = provisionerId;
  pigeonResult.addressRange = addressRange;
  return pigeonResult;
}
+ (Provisioner *)fromList:(NSArray<id> *)list {
  Provisioner *pigeonResult = [[Provisioner alloc] init];
  pigeonResult.name = GetNullableObjectAtIndex(list, 0);
  pigeonResult.provisionerId = GetNullableObjectAtIndex(list, 1);
  pigeonResult.addressRange = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable Provisioner *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Provisioner fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.name ?: [NSNull null],
    self.provisionerId ?: [NSNull null],
    self.addressRange ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  Provisioner *other = (Provisioner *)object;
  return FLTPigeonDeepEquals(self.name, other.name) && FLTPigeonDeepEquals(self.provisionerId, other.provisionerId) && FLTPigeonDeepEquals(self.addressRange, other.addressRange);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + FLTPigeonDeepHash(self.provisionerId);
  result = result * 31 + FLTPigeonDeepHash(self.addressRange);
  return result;
}
@end

@implementation UnprovisionedDevice
+ (instancetype)makeWithDeviceId:(NSString *)deviceId
    name:(NSString *)name
    rssi:(NSInteger )rssi
    uuid:(NSArray<NSNumber *> *)uuid {
  UnprovisionedDevice* pigeonResult = [[UnprovisionedDevice alloc] init];
  pigeonResult.deviceId = deviceId;
  pigeonResult.name = name;
  pigeonResult.rssi = rssi;
  pigeonResult.uuid = uuid;
  return pigeonResult;
}
+ (UnprovisionedDevice *)fromList:(NSArray<id> *)list {
  UnprovisionedDevice *pigeonResult = [[UnprovisionedDevice alloc] init];
  pigeonResult.deviceId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.rssi = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.uuid = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable UnprovisionedDevice *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [UnprovisionedDevice fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.deviceId ?: [NSNull null],
    self.name ?: [NSNull null],
    @(self.rssi),
    self.uuid ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  UnprovisionedDevice *other = (UnprovisionedDevice *)object;
  return FLTPigeonDeepEquals(self.deviceId, other.deviceId) && FLTPigeonDeepEquals(self.name, other.name) && self.rssi == other.rssi && FLTPigeonDeepEquals(self.uuid, other.uuid);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.deviceId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + @(self.rssi).hash;
  result = result * 31 + FLTPigeonDeepHash(self.uuid);
  return result;
}
@end

@implementation ProvisionedNode
+ (instancetype)makeWithNodeId:(NSString *)nodeId
    name:(NSString *)name
    unicastAddress:(NSInteger )unicastAddress
    uuid:(NSArray<NSNumber *> *)uuid
    elements:(NSArray<Element *> *)elements
    provisioned:(BOOL )provisioned {
  ProvisionedNode* pigeonResult = [[ProvisionedNode alloc] init];
  pigeonResult.nodeId = nodeId;
  pigeonResult.name = name;
  pigeonResult.unicastAddress = unicastAddress;
  pigeonResult.uuid = uuid;
  pigeonResult.elements = elements;
  pigeonResult.provisioned = provisioned;
  return pigeonResult;
}
+ (ProvisionedNode *)fromList:(NSArray<id> *)list {
  ProvisionedNode *pigeonResult = [[ProvisionedNode alloc] init];
  pigeonResult.nodeId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.unicastAddress = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.uuid = GetNullableObjectAtIndex(list, 3);
  pigeonResult.elements = GetNullableObjectAtIndex(list, 4);
  pigeonResult.provisioned = [GetNullableObjectAtIndex(list, 5) boolValue];
  return pigeonResult;
}
+ (nullable ProvisionedNode *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ProvisionedNode fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.nodeId ?: [NSNull null],
    self.name ?: [NSNull null],
    @(self.unicastAddress),
    self.uuid ?: [NSNull null],
    self.elements ?: [NSNull null],
    @(self.provisioned),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  ProvisionedNode *other = (ProvisionedNode *)object;
  return FLTPigeonDeepEquals(self.nodeId, other.nodeId) && FLTPigeonDeepEquals(self.name, other.name) && self.unicastAddress == other.unicastAddress && FLTPigeonDeepEquals(self.uuid, other.uuid) && FLTPigeonDeepEquals(self.elements, other.elements) && self.provisioned == other.provisioned;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.nodeId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + @(self.unicastAddress).hash;
  result = result * 31 + FLTPigeonDeepHash(self.uuid);
  result = result * 31 + FLTPigeonDeepHash(self.elements);
  result = result * 31 + @(self.provisioned).hash;
  return result;
}
@end

@implementation Element
+ (instancetype)makeWithAddress:(NSInteger )address
    models:(NSArray<Model *> *)models {
  Element* pigeonResult = [[Element alloc] init];
  pigeonResult.address = address;
  pigeonResult.models = models;
  return pigeonResult;
}
+ (Element *)fromList:(NSArray<id> *)list {
  Element *pigeonResult = [[Element alloc] init];
  pigeonResult.address = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.models = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable Element *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Element fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.address),
    self.models ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  Element *other = (Element *)object;
  return self.address == other.address && FLTPigeonDeepEquals(self.models, other.models);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.address).hash;
  result = result * 31 + FLTPigeonDeepHash(self.models);
  return result;
}
@end

@implementation Model
+ (instancetype)makeWithModelId:(NSInteger )modelId
    modelName:(NSString *)modelName
    publishable:(BOOL )publishable
    subscribable:(BOOL )subscribable {
  Model* pigeonResult = [[Model alloc] init];
  pigeonResult.modelId = modelId;
  pigeonResult.modelName = modelName;
  pigeonResult.publishable = publishable;
  pigeonResult.subscribable = subscribable;
  return pigeonResult;
}
+ (Model *)fromList:(NSArray<id> *)list {
  Model *pigeonResult = [[Model alloc] init];
  pigeonResult.modelId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.modelName = GetNullableObjectAtIndex(list, 1);
  pigeonResult.publishable = [GetNullableObjectAtIndex(list, 2) boolValue];
  pigeonResult.subscribable = [GetNullableObjectAtIndex(list, 3) boolValue];
  return pigeonResult;
}
+ (nullable Model *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Model fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.modelId),
    self.modelName ?: [NSNull null],
    @(self.publishable),
    @(self.subscribable),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  Model *other = (Model *)object;
  return self.modelId == other.modelId && FLTPigeonDeepEquals(self.modelName, other.modelName) && self.publishable == other.publishable && self.subscribable == other.subscribable;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.modelId).hash;
  result = result * 31 + FLTPigeonDeepHash(self.modelName);
  result = result * 31 + @(self.publishable).hash;
  result = result * 31 + @(self.subscribable).hash;
  return result;
}
@end

@implementation MeshGroup
+ (instancetype)makeWithGroupId:(NSString *)groupId
    name:(NSString *)name
    address:(NSInteger )address
    nodeIds:(NSArray<NSString *> *)nodeIds {
  MeshGroup* pigeonResult = [[MeshGroup alloc] init];
  pigeonResult.groupId = groupId;
  pigeonResult.name = name;
  pigeonResult.address = address;
  pigeonResult.nodeIds = nodeIds;
  return pigeonResult;
}
+ (MeshGroup *)fromList:(NSArray<id> *)list {
  MeshGroup *pigeonResult = [[MeshGroup alloc] init];
  pigeonResult.groupId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.address = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.nodeIds = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable MeshGroup *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MeshGroup fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.groupId ?: [NSNull null],
    self.name ?: [NSNull null],
    @(self.address),
    self.nodeIds ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  MeshGroup *other = (MeshGroup *)object;
  return FLTPigeonDeepEquals(self.groupId, other.groupId) && FLTPigeonDeepEquals(self.name, other.name) && self.address == other.address && FLTPigeonDeepEquals(self.nodeIds, other.nodeIds);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.groupId);
  result = result * 31 + FLTPigeonDeepHash(self.name);
  result = result * 31 + @(self.address).hash;
  result = result * 31 + FLTPigeonDeepHash(self.nodeIds);
  return result;
}
@end

@implementation MeshMessage
+ (instancetype)makeWithOpcode:(NSInteger )opcode
    address:(NSInteger )address
    appKeyIndex:(NSInteger )appKeyIndex
    parameters:(NSDictionary<NSString *, id> *)parameters {
  MeshMessage* pigeonResult = [[MeshMessage alloc] init];
  pigeonResult.opcode = opcode;
  pigeonResult.address = address;
  pigeonResult.appKeyIndex = appKeyIndex;
  pigeonResult.parameters = parameters;
  return pigeonResult;
}
+ (MeshMessage *)fromList:(NSArray<id> *)list {
  MeshMessage *pigeonResult = [[MeshMessage alloc] init];
  pigeonResult.opcode = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.address = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.appKeyIndex = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.parameters = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable MeshMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MeshMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.opcode),
    @(self.address),
    @(self.appKeyIndex),
    self.parameters ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  MeshMessage *other = (MeshMessage *)object;
  return self.opcode == other.opcode && self.address == other.address && self.appKeyIndex == other.appKeyIndex && FLTPigeonDeepEquals(self.parameters, other.parameters);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.opcode).hash;
  result = result * 31 + @(self.address).hash;
  result = result * 31 + @(self.appKeyIndex).hash;
  result = result * 31 + FLTPigeonDeepHash(self.parameters);
  return result;
}
@end

@implementation ProvisioningParameters
+ (instancetype)makeWithDeviceName:(NSString *)deviceName
    oobMethod:(nullable NSNumber *)oobMethod
    oobData:(nullable NSString *)oobData
    enablePrivacy:(BOOL )enablePrivacy {
  ProvisioningParameters* pigeonResult = [[ProvisioningParameters alloc] init];
  pigeonResult.deviceName = deviceName;
  pigeonResult.oobMethod = oobMethod;
  pigeonResult.oobData = oobData;
  pigeonResult.enablePrivacy = enablePrivacy;
  return pigeonResult;
}
+ (ProvisioningParameters *)fromList:(NSArray<id> *)list {
  ProvisioningParameters *pigeonResult = [[ProvisioningParameters alloc] init];
  pigeonResult.deviceName = GetNullableObjectAtIndex(list, 0);
  pigeonResult.oobMethod = GetNullableObjectAtIndex(list, 1);
  pigeonResult.oobData = GetNullableObjectAtIndex(list, 2);
  pigeonResult.enablePrivacy = [GetNullableObjectAtIndex(list, 3) boolValue];
  return pigeonResult;
}
+ (nullable ProvisioningParameters *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ProvisioningParameters fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.deviceName ?: [NSNull null],
    self.oobMethod ?: [NSNull null],
    self.oobData ?: [NSNull null],
    @(self.enablePrivacy),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  ProvisioningParameters *other = (ProvisioningParameters *)object;
  return FLTPigeonDeepEquals(self.deviceName, other.deviceName) && FLTPigeonDeepEquals(self.oobMethod, other.oobMethod) && FLTPigeonDeepEquals(self.oobData, other.oobData) && self.enablePrivacy == other.enablePrivacy;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.deviceName);
  result = result * 31 + FLTPigeonDeepHash(self.oobMethod);
  result = result * 31 + FLTPigeonDeepHash(self.oobData);
  result = result * 31 + @(self.enablePrivacy).hash;
  return result;
}
@end

@implementation GenericOnOffSet
+ (instancetype)makeWithState:(BOOL )state
    transitionTime:(NSInteger )transitionTime
    delay:(NSInteger )delay {
  GenericOnOffSet* pigeonResult = [[GenericOnOffSet alloc] init];
  pigeonResult.state = state;
  pigeonResult.transitionTime = transitionTime;
  pigeonResult.delay = delay;
  return pigeonResult;
}
+ (GenericOnOffSet *)fromList:(NSArray<id> *)list {
  GenericOnOffSet *pigeonResult = [[GenericOnOffSet alloc] init];
  pigeonResult.state = [GetNullableObjectAtIndex(list, 0) boolValue];
  pigeonResult.transitionTime = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.delay = [GetNullableObjectAtIndex(list, 2) integerValue];
  return pigeonResult;
}
+ (nullable GenericOnOffSet *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [GenericOnOffSet fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.state),
    @(self.transitionTime),
    @(self.delay),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  GenericOnOffSet *other = (GenericOnOffSet *)object;
  return self.state == other.state && self.transitionTime == other.transitionTime && self.delay == other.delay;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.state).hash;
  result = result * 31 + @(self.transitionTime).hash;
  result = result * 31 + @(self.delay).hash;
  return result;
}
@end

@implementation GenericLevelSet
+ (instancetype)makeWithLevel:(NSInteger )level
    transitionTime:(NSInteger )transitionTime
    delay:(NSInteger )delay {
  GenericLevelSet* pigeonResult = [[GenericLevelSet alloc] init];
  pigeonResult.level = level;
  pigeonResult.transitionTime = transitionTime;
  pigeonResult.delay = delay;
  return pigeonResult;
}
+ (GenericLevelSet *)fromList:(NSArray<id> *)list {
  GenericLevelSet *pigeonResult = [[GenericLevelSet alloc] init];
  pigeonResult.level = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.transitionTime = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.delay = [GetNullableObjectAtIndex(list, 2) integerValue];
  return pigeonResult;
}
+ (nullable GenericLevelSet *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [GenericLevelSet fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.level),
    @(self.transitionTime),
    @(self.delay),
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  GenericLevelSet *other = (GenericLevelSet *)object;
  return self.level == other.level && self.transitionTime == other.transitionTime && self.delay == other.delay;
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + @(self.level).hash;
  result = result * 31 + @(self.transitionTime).hash;
  result = result * 31 + @(self.delay).hash;
  return result;
}
@end

@interface nullPigeonGeneratedPigeonCodecReader : FlutterStandardReader
@end
@implementation nullPigeonGeneratedPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [MeshNetwork fromList:[self readValue]];
    case 130: 
      return [NetworkKey fromList:[self readValue]];
    case 131: 
      return [AppKey fromList:[self readValue]];
    case 132: 
      return [Provisioner fromList:[self readValue]];
    case 133: 
      return [UnprovisionedDevice fromList:[self readValue]];
    case 134: 
      return [ProvisionedNode fromList:[self readValue]];
    case 135: 
      return [Element fromList:[self readValue]];
    case 136: 
      return [Model fromList:[self readValue]];
    case 137: 
      return [MeshGroup fromList:[self readValue]];
    case 138: 
      return [MeshMessage fromList:[self readValue]];
    case 139: 
      return [ProvisioningParameters fromList:[self readValue]];
    case 140: 
      return [GenericOnOffSet fromList:[self readValue]];
    case 141: 
      return [GenericLevelSet fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullPigeonGeneratedPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullPigeonGeneratedPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[MeshNetwork class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[NetworkKey class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[AppKey class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Provisioner class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[UnprovisionedDevice class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ProvisionedNode class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Element class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Model class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MeshGroup class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MeshMessage class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ProvisioningParameters class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[GenericOnOffSet class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[GenericLevelSet class]]) {
    [self writeByte:141];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullPigeonGeneratedPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullPigeonGeneratedPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullPigeonGeneratedPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullPigeonGeneratedPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetPigeonGeneratedCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullPigeonGeneratedPigeonCodecReaderWriter *readerWriter = [[nullPigeonGeneratedPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpMeshApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MeshApi> *api) {
  SetUpMeshApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpMeshApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MeshApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createNetworkName:error:)], @"MeshApi api (%@) doesn't respond to @selector(createNetworkName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_name = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        MeshNetwork *output = [api createNetworkName:arg_name error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.loadNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(loadNetworkWithError:)], @"MeshApi api (%@) doesn't respond to @selector(loadNetworkWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        MeshNetwork *output = [api loadNetworkWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.saveNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(saveNetworkWithError:)], @"MeshApi api (%@) doesn't respond to @selector(saveNetworkWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api saveNetworkWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.exportNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(exportNetworkPath:error:)], @"MeshApi api (%@) doesn't respond to @selector(exportNetworkPath:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_path = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api exportNetworkPath:arg_path error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.importNetwork", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(importNetworkPath:error:)], @"MeshApi api (%@) doesn't respond to @selector(importNetworkPath:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_path = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api importNetworkPath:arg_path error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.startScan", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startScanWithError:)], @"MeshApi api (%@) doesn't respond to @selector(startScanWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api startScanWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.stopScan", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopScanWithError:)], @"MeshApi api (%@) doesn't respond to @selector(stopScanWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopScanWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provisionDevice", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(provisionDeviceDevice:params:error:)], @"MeshApi api (%@) doesn't respond to @selector(provisionDeviceDevice:params:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        UnprovisionedDevice *arg_device = GetNullableObjectAtIndex(args, 0);
        ProvisioningParameters *arg_params = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        ProvisionedNode *output = [api provisionDeviceDevice:arg_device params:arg_params error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.sendMessage", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendMessageMessage:error:)], @"MeshApi api (%@) doesn't respond to @selector(sendMessageMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        MeshMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api sendMessageMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getNodes", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getNodesWithError:)], @"MeshApi api (%@) doesn't respond to @selector(getNodesWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<ProvisionedNode *> *output = [api getNodesWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeNode", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(removeNodeNodeId:error:)], @"MeshApi api (%@) doesn't respond to @selector(removeNodeNodeId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_nodeId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api removeNodeNodeId:arg_nodeId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createGroup", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createGroupName:error:)], @"MeshApi api (%@) doesn't respond to @selector(createGroupName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_name = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        MeshGroup *output = [api createGroupName:arg_name error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getGroups", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getGroupsWithError:)], @"MeshApi api (%@) doesn't respond to @selector(getGroupsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<MeshGroup *> *output = [api getGroupsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addNodeToGroup", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(addNodeToGroupNodeId:groupId:error:)], @"MeshApi api (%@) doesn't respond to @selector(addNodeToGroupNodeId:groupId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_nodeId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_groupId = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api addNodeToGroupNodeId:arg_nodeId groupId:arg_groupId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface MeshFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation MeshFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onDeviceDiscoveredDevice:(UnprovisionedDevice *)arg_device completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onDeviceDiscovered", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonGeneratedCodec()];
  [channel sendMessage:@[arg_device ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onMessageReceivedMessage:(MeshMessage *)arg_message completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onMessageReceived", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonGeneratedCodec()];
  [channel sendMessage:@[arg_message ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

