// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPigeonGenerated(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPigeonGenerated(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPigeonGenerated(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPigeonGenerated(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPigeonGenerated(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPigeonGenerated(lhsKey, rhsKey) {
          if deepEqualsPigeonGenerated(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPigeonGenerated(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPigeonGenerated(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPigeonGenerated(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPigeonGenerated(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPigeonGenerated(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPigeonGenerated(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPigeonGenerated(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum RxMetadataStatus: Int {
  case available = 0
  case unavailable = 1
}

enum ProvisioningEventType: Int {
  case started = 0
  case capabilitiesReceived = 1
  case oobInputRequested = 2
  case oobOutputRequested = 3
  case provisioningCompleted = 4
  case failed = 5
}

/// Generated class from Pigeon that represents data sent in messages.
struct MeshNetwork: Hashable {
  var networkId: String? = nil
  var name: String? = nil
  var networkKeys: [NetworkKey]? = nil
  var appKeys: [AppKey]? = nil
  var nodes: [ProvisionedNode]? = nil
  var groups: [MeshGroup]? = nil
  var provisioner: Provisioner? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MeshNetwork? {
    let networkId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let networkKeys: [NetworkKey]? = nilOrValue(pigeonVar_list[2])
    let appKeys: [AppKey]? = nilOrValue(pigeonVar_list[3])
    let nodes: [ProvisionedNode]? = nilOrValue(pigeonVar_list[4])
    let groups: [MeshGroup]? = nilOrValue(pigeonVar_list[5])
    let provisioner: Provisioner? = nilOrValue(pigeonVar_list[6])

    return MeshNetwork(
      networkId: networkId,
      name: name,
      networkKeys: networkKeys,
      appKeys: appKeys,
      nodes: nodes,
      groups: groups,
      provisioner: provisioner
    )
  }
  func toList() -> [Any?] {
    return [
      networkId,
      name,
      networkKeys,
      appKeys,
      nodes,
      groups,
      provisioner,
    ]
  }
  static func == (lhs: MeshNetwork, rhs: MeshNetwork) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.networkId, rhs.networkId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.networkKeys, rhs.networkKeys) && deepEqualsPigeonGenerated(lhs.appKeys, rhs.appKeys) && deepEqualsPigeonGenerated(lhs.nodes, rhs.nodes) && deepEqualsPigeonGenerated(lhs.groups, rhs.groups) && deepEqualsPigeonGenerated(lhs.provisioner, rhs.provisioner)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MeshNetwork")
    deepHashPigeonGenerated(value: networkId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: networkKeys, hasher: &hasher)
    deepHashPigeonGenerated(value: appKeys, hasher: &hasher)
    deepHashPigeonGenerated(value: nodes, hasher: &hasher)
    deepHashPigeonGenerated(value: groups, hasher: &hasher)
    deepHashPigeonGenerated(value: provisioner, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NetworkKey: Hashable {
  var keyId: String? = nil
  var key: String? = nil
  var index: Int64? = nil
  var enabled: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NetworkKey? {
    let keyId: String? = nilOrValue(pigeonVar_list[0])
    let key: String? = nilOrValue(pigeonVar_list[1])
    let index: Int64? = nilOrValue(pigeonVar_list[2])
    let enabled: Bool? = nilOrValue(pigeonVar_list[3])

    return NetworkKey(
      keyId: keyId,
      key: key,
      index: index,
      enabled: enabled
    )
  }
  func toList() -> [Any?] {
    return [
      keyId,
      key,
      index,
      enabled,
    ]
  }
  static func == (lhs: NetworkKey, rhs: NetworkKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.keyId, rhs.keyId) && deepEqualsPigeonGenerated(lhs.key, rhs.key) && deepEqualsPigeonGenerated(lhs.index, rhs.index) && deepEqualsPigeonGenerated(lhs.enabled, rhs.enabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NetworkKey")
    deepHashPigeonGenerated(value: keyId, hasher: &hasher)
    deepHashPigeonGenerated(value: key, hasher: &hasher)
    deepHashPigeonGenerated(value: index, hasher: &hasher)
    deepHashPigeonGenerated(value: enabled, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppKey: Hashable {
  var keyId: String? = nil
  var key: String? = nil
  var index: Int64? = nil
  var enabled: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppKey? {
    let keyId: String? = nilOrValue(pigeonVar_list[0])
    let key: String? = nilOrValue(pigeonVar_list[1])
    let index: Int64? = nilOrValue(pigeonVar_list[2])
    let enabled: Bool? = nilOrValue(pigeonVar_list[3])

    return AppKey(
      keyId: keyId,
      key: key,
      index: index,
      enabled: enabled
    )
  }
  func toList() -> [Any?] {
    return [
      keyId,
      key,
      index,
      enabled,
    ]
  }
  static func == (lhs: AppKey, rhs: AppKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.keyId, rhs.keyId) && deepEqualsPigeonGenerated(lhs.key, rhs.key) && deepEqualsPigeonGenerated(lhs.index, rhs.index) && deepEqualsPigeonGenerated(lhs.enabled, rhs.enabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AppKey")
    deepHashPigeonGenerated(value: keyId, hasher: &hasher)
    deepHashPigeonGenerated(value: key, hasher: &hasher)
    deepHashPigeonGenerated(value: index, hasher: &hasher)
    deepHashPigeonGenerated(value: enabled, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Provisioner: Hashable {
  var name: String? = nil
  var provisionerId: String? = nil
  var addressRange: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Provisioner? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let provisionerId: String? = nilOrValue(pigeonVar_list[1])
    let addressRange: [Int64]? = nilOrValue(pigeonVar_list[2])

    return Provisioner(
      name: name,
      provisionerId: provisionerId,
      addressRange: addressRange
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      provisionerId,
      addressRange,
    ]
  }
  static func == (lhs: Provisioner, rhs: Provisioner) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.provisionerId, rhs.provisionerId) && deepEqualsPigeonGenerated(lhs.addressRange, rhs.addressRange)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Provisioner")
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: provisionerId, hasher: &hasher)
    deepHashPigeonGenerated(value: addressRange, hasher: &hasher)
  }
}

/// Pigeon transport model for unprovisioned devices.
///
/// Named to avoid clashing with Nordic iOS library types.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FlutterUnprovisionedDevice: Hashable {
  var deviceId: String? = nil
  var name: String? = nil
  var rssi: Int64? = nil
  var uuid: [Int64]? = nil
  var serviceUuid: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FlutterUnprovisionedDevice? {
    let deviceId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi: Int64? = nilOrValue(pigeonVar_list[2])
    let uuid: [Int64]? = nilOrValue(pigeonVar_list[3])
    let serviceUuid: String? = nilOrValue(pigeonVar_list[4])

    return FlutterUnprovisionedDevice(
      deviceId: deviceId,
      name: name,
      rssi: rssi,
      uuid: uuid,
      serviceUuid: serviceUuid
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      name,
      rssi,
      uuid,
      serviceUuid,
    ]
  }
  static func == (lhs: FlutterUnprovisionedDevice, rhs: FlutterUnprovisionedDevice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.deviceId, rhs.deviceId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.rssi, rhs.rssi) && deepEqualsPigeonGenerated(lhs.uuid, rhs.uuid) && deepEqualsPigeonGenerated(lhs.serviceUuid, rhs.serviceUuid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FlutterUnprovisionedDevice")
    deepHashPigeonGenerated(value: deviceId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: rssi, hasher: &hasher)
    deepHashPigeonGenerated(value: uuid, hasher: &hasher)
    deepHashPigeonGenerated(value: serviceUuid, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProvisionedNode: Hashable {
  var nodeId: String? = nil
  var name: String? = nil
  var unicastAddress: Int64? = nil
  var uuid: [Int64]? = nil
  var elements: [Element]? = nil
  var provisioned: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisionedNode? {
    let nodeId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let unicastAddress: Int64? = nilOrValue(pigeonVar_list[2])
    let uuid: [Int64]? = nilOrValue(pigeonVar_list[3])
    let elements: [Element]? = nilOrValue(pigeonVar_list[4])
    let provisioned: Bool? = nilOrValue(pigeonVar_list[5])

    return ProvisionedNode(
      nodeId: nodeId,
      name: name,
      unicastAddress: unicastAddress,
      uuid: uuid,
      elements: elements,
      provisioned: provisioned
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      name,
      unicastAddress,
      uuid,
      elements,
      provisioned,
    ]
  }
  static func == (lhs: ProvisionedNode, rhs: ProvisionedNode) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.nodeId, rhs.nodeId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.unicastAddress, rhs.unicastAddress) && deepEqualsPigeonGenerated(lhs.uuid, rhs.uuid) && deepEqualsPigeonGenerated(lhs.elements, rhs.elements) && deepEqualsPigeonGenerated(lhs.provisioned, rhs.provisioned)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisionedNode")
    deepHashPigeonGenerated(value: nodeId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: unicastAddress, hasher: &hasher)
    deepHashPigeonGenerated(value: uuid, hasher: &hasher)
    deepHashPigeonGenerated(value: elements, hasher: &hasher)
    deepHashPigeonGenerated(value: provisioned, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Element: Hashable {
  var address: Int64? = nil
  var models: [Model]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Element? {
    let address: Int64? = nilOrValue(pigeonVar_list[0])
    let models: [Model]? = nilOrValue(pigeonVar_list[1])

    return Element(
      address: address,
      models: models
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      models,
    ]
  }
  static func == (lhs: Element, rhs: Element) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.address, rhs.address) && deepEqualsPigeonGenerated(lhs.models, rhs.models)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Element")
    deepHashPigeonGenerated(value: address, hasher: &hasher)
    deepHashPigeonGenerated(value: models, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Model: Hashable {
  var modelId: Int64? = nil
  var modelName: String? = nil
  var publishable: Bool? = nil
  var subscribable: Bool? = nil
  var boundAppKeyIndexes: [Int64]? = nil
  var subscriptions: [Int64]? = nil
  var publication: Publication? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Model? {
    let modelId: Int64? = nilOrValue(pigeonVar_list[0])
    let modelName: String? = nilOrValue(pigeonVar_list[1])
    let publishable: Bool? = nilOrValue(pigeonVar_list[2])
    let subscribable: Bool? = nilOrValue(pigeonVar_list[3])
    let boundAppKeyIndexes: [Int64]? = nilOrValue(pigeonVar_list[4])
    let subscriptions: [Int64]? = nilOrValue(pigeonVar_list[5])
    let publication: Publication? = nilOrValue(pigeonVar_list[6])

    return Model(
      modelId: modelId,
      modelName: modelName,
      publishable: publishable,
      subscribable: subscribable,
      boundAppKeyIndexes: boundAppKeyIndexes,
      subscriptions: subscriptions,
      publication: publication
    )
  }
  func toList() -> [Any?] {
    return [
      modelId,
      modelName,
      publishable,
      subscribable,
      boundAppKeyIndexes,
      subscriptions,
      publication,
    ]
  }
  static func == (lhs: Model, rhs: Model) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.modelId, rhs.modelId) && deepEqualsPigeonGenerated(lhs.modelName, rhs.modelName) && deepEqualsPigeonGenerated(lhs.publishable, rhs.publishable) && deepEqualsPigeonGenerated(lhs.subscribable, rhs.subscribable) && deepEqualsPigeonGenerated(lhs.boundAppKeyIndexes, rhs.boundAppKeyIndexes) && deepEqualsPigeonGenerated(lhs.subscriptions, rhs.subscriptions) && deepEqualsPigeonGenerated(lhs.publication, rhs.publication)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Model")
    deepHashPigeonGenerated(value: modelId, hasher: &hasher)
    deepHashPigeonGenerated(value: modelName, hasher: &hasher)
    deepHashPigeonGenerated(value: publishable, hasher: &hasher)
    deepHashPigeonGenerated(value: subscribable, hasher: &hasher)
    deepHashPigeonGenerated(value: boundAppKeyIndexes, hasher: &hasher)
    deepHashPigeonGenerated(value: subscriptions, hasher: &hasher)
    deepHashPigeonGenerated(value: publication, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Publication: Hashable {
  var address: Int64? = nil
  var appKeyIndex: Int64? = nil
  var ttl: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Publication? {
    let address: Int64? = nilOrValue(pigeonVar_list[0])
    let appKeyIndex: Int64? = nilOrValue(pigeonVar_list[1])
    let ttl: Int64? = nilOrValue(pigeonVar_list[2])

    return Publication(
      address: address,
      appKeyIndex: appKeyIndex,
      ttl: ttl
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      appKeyIndex,
      ttl,
    ]
  }
  static func == (lhs: Publication, rhs: Publication) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.address, rhs.address) && deepEqualsPigeonGenerated(lhs.appKeyIndex, rhs.appKeyIndex) && deepEqualsPigeonGenerated(lhs.ttl, rhs.ttl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Publication")
    deepHashPigeonGenerated(value: address, hasher: &hasher)
    deepHashPigeonGenerated(value: appKeyIndex, hasher: &hasher)
    deepHashPigeonGenerated(value: ttl, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MeshGroup: Hashable {
  var groupId: String? = nil
  var name: String? = nil
  var address: Int64? = nil
  var nodeIds: [String]? = nil
  /// 16-byte Label UUID (MSB..LSB) when this is a virtual group, otherwise null/empty.
  var labelUuid: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MeshGroup? {
    let groupId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let address: Int64? = nilOrValue(pigeonVar_list[2])
    let nodeIds: [String]? = nilOrValue(pigeonVar_list[3])
    let labelUuid: [Int64]? = nilOrValue(pigeonVar_list[4])

    return MeshGroup(
      groupId: groupId,
      name: name,
      address: address,
      nodeIds: nodeIds,
      labelUuid: labelUuid
    )
  }
  func toList() -> [Any?] {
    return [
      groupId,
      name,
      address,
      nodeIds,
      labelUuid,
    ]
  }
  static func == (lhs: MeshGroup, rhs: MeshGroup) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.groupId, rhs.groupId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.address, rhs.address) && deepEqualsPigeonGenerated(lhs.nodeIds, rhs.nodeIds) && deepEqualsPigeonGenerated(lhs.labelUuid, rhs.labelUuid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MeshGroup")
    deepHashPigeonGenerated(value: groupId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: address, hasher: &hasher)
    deepHashPigeonGenerated(value: nodeIds, hasher: &hasher)
    deepHashPigeonGenerated(value: labelUuid, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MeshMessage: Hashable {
  var opcode: Int64? = nil
  var address: Int64? = nil
  var appKeyIndex: Int64? = nil
  var parameters: [String: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MeshMessage? {
    let opcode: Int64? = nilOrValue(pigeonVar_list[0])
    let address: Int64? = nilOrValue(pigeonVar_list[1])
    let appKeyIndex: Int64? = nilOrValue(pigeonVar_list[2])
    let parameters: [String: Any?]? = nilOrValue(pigeonVar_list[3])

    return MeshMessage(
      opcode: opcode,
      address: address,
      appKeyIndex: appKeyIndex,
      parameters: parameters
    )
  }
  func toList() -> [Any?] {
    return [
      opcode,
      address,
      appKeyIndex,
      parameters,
    ]
  }
  static func == (lhs: MeshMessage, rhs: MeshMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.opcode, rhs.opcode) && deepEqualsPigeonGenerated(lhs.address, rhs.address) && deepEqualsPigeonGenerated(lhs.appKeyIndex, rhs.appKeyIndex) && deepEqualsPigeonGenerated(lhs.parameters, rhs.parameters)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MeshMessage")
    deepHashPigeonGenerated(value: opcode, hasher: &hasher)
    deepHashPigeonGenerated(value: address, hasher: &hasher)
    deepHashPigeonGenerated(value: appKeyIndex, hasher: &hasher)
    deepHashPigeonGenerated(value: parameters, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RxAccessMessage: Hashable {
  var opcode: Int64? = nil
  /// Access message parameters (raw bytes).
  var parameters: [Int64]? = nil
  /// Best-effort source address (unicast), if available.
  var source: Int64? = nil
  /// Best-effort destination address, if available.
  var destination: Int64? = nil
  var metadataStatus: RxMetadataStatus? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RxAccessMessage? {
    let opcode: Int64? = nilOrValue(pigeonVar_list[0])
    let parameters: [Int64]? = nilOrValue(pigeonVar_list[1])
    let source: Int64? = nilOrValue(pigeonVar_list[2])
    let destination: Int64? = nilOrValue(pigeonVar_list[3])
    let metadataStatus: RxMetadataStatus? = nilOrValue(pigeonVar_list[4])

    return RxAccessMessage(
      opcode: opcode,
      parameters: parameters,
      source: source,
      destination: destination,
      metadataStatus: metadataStatus
    )
  }
  func toList() -> [Any?] {
    return [
      opcode,
      parameters,
      source,
      destination,
      metadataStatus,
    ]
  }
  static func == (lhs: RxAccessMessage, rhs: RxAccessMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.opcode, rhs.opcode) && deepEqualsPigeonGenerated(lhs.parameters, rhs.parameters) && deepEqualsPigeonGenerated(lhs.source, rhs.source) && deepEqualsPigeonGenerated(lhs.destination, rhs.destination) && deepEqualsPigeonGenerated(lhs.metadataStatus, rhs.metadataStatus)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RxAccessMessage")
    deepHashPigeonGenerated(value: opcode, hasher: &hasher)
    deepHashPigeonGenerated(value: parameters, hasher: &hasher)
    deepHashPigeonGenerated(value: source, hasher: &hasher)
    deepHashPigeonGenerated(value: destination, hasher: &hasher)
    deepHashPigeonGenerated(value: metadataStatus, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProvisioningParameters: Hashable {
  var deviceName: String? = nil
  var oobMethod: Int64? = nil
  var oobData: String? = nil
  var enablePrivacy: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisioningParameters? {
    let deviceName: String? = nilOrValue(pigeonVar_list[0])
    let oobMethod: Int64? = nilOrValue(pigeonVar_list[1])
    let oobData: String? = nilOrValue(pigeonVar_list[2])
    let enablePrivacy: Bool? = nilOrValue(pigeonVar_list[3])

    return ProvisioningParameters(
      deviceName: deviceName,
      oobMethod: oobMethod,
      oobData: oobData,
      enablePrivacy: enablePrivacy
    )
  }
  func toList() -> [Any?] {
    return [
      deviceName,
      oobMethod,
      oobData,
      enablePrivacy,
    ]
  }
  static func == (lhs: ProvisioningParameters, rhs: ProvisioningParameters) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.deviceName, rhs.deviceName) && deepEqualsPigeonGenerated(lhs.oobMethod, rhs.oobMethod) && deepEqualsPigeonGenerated(lhs.oobData, rhs.oobData) && deepEqualsPigeonGenerated(lhs.enablePrivacy, rhs.enablePrivacy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisioningParameters")
    deepHashPigeonGenerated(value: deviceName, hasher: &hasher)
    deepHashPigeonGenerated(value: oobMethod, hasher: &hasher)
    deepHashPigeonGenerated(value: oobData, hasher: &hasher)
    deepHashPigeonGenerated(value: enablePrivacy, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProvisioningEvent: Hashable {
  var deviceId: String? = nil
  var type: ProvisioningEventType? = nil
  var message: String? = nil
  var progress: Int64? = nil
  var attentionTimer: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisioningEvent? {
    let deviceId: String? = nilOrValue(pigeonVar_list[0])
    let type: ProvisioningEventType? = nilOrValue(pigeonVar_list[1])
    let message: String? = nilOrValue(pigeonVar_list[2])
    let progress: Int64? = nilOrValue(pigeonVar_list[3])
    let attentionTimer: Int64? = nilOrValue(pigeonVar_list[4])

    return ProvisioningEvent(
      deviceId: deviceId,
      type: type,
      message: message,
      progress: progress,
      attentionTimer: attentionTimer
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      type,
      message,
      progress,
      attentionTimer,
    ]
  }
  static func == (lhs: ProvisioningEvent, rhs: ProvisioningEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.deviceId, rhs.deviceId) && deepEqualsPigeonGenerated(lhs.type, rhs.type) && deepEqualsPigeonGenerated(lhs.message, rhs.message) && deepEqualsPigeonGenerated(lhs.progress, rhs.progress) && deepEqualsPigeonGenerated(lhs.attentionTimer, rhs.attentionTimer)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisioningEvent")
    deepHashPigeonGenerated(value: deviceId, hasher: &hasher)
    deepHashPigeonGenerated(value: type, hasher: &hasher)
    deepHashPigeonGenerated(value: message, hasher: &hasher)
    deepHashPigeonGenerated(value: progress, hasher: &hasher)
    deepHashPigeonGenerated(value: attentionTimer, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GenericOnOffSet: Hashable {
  var state: Bool? = nil
  var transitionTime: Int64? = nil
  var delay: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenericOnOffSet? {
    let state: Bool? = nilOrValue(pigeonVar_list[0])
    let transitionTime: Int64? = nilOrValue(pigeonVar_list[1])
    let delay: Int64? = nilOrValue(pigeonVar_list[2])

    return GenericOnOffSet(
      state: state,
      transitionTime: transitionTime,
      delay: delay
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      transitionTime,
      delay,
    ]
  }
  static func == (lhs: GenericOnOffSet, rhs: GenericOnOffSet) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.state, rhs.state) && deepEqualsPigeonGenerated(lhs.transitionTime, rhs.transitionTime) && deepEqualsPigeonGenerated(lhs.delay, rhs.delay)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenericOnOffSet")
    deepHashPigeonGenerated(value: state, hasher: &hasher)
    deepHashPigeonGenerated(value: transitionTime, hasher: &hasher)
    deepHashPigeonGenerated(value: delay, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GenericLevelSet: Hashable {
  var level: Int64? = nil
  var transitionTime: Int64? = nil
  var delay: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenericLevelSet? {
    let level: Int64? = nilOrValue(pigeonVar_list[0])
    let transitionTime: Int64? = nilOrValue(pigeonVar_list[1])
    let delay: Int64? = nilOrValue(pigeonVar_list[2])

    return GenericLevelSet(
      level: level,
      transitionTime: transitionTime,
      delay: delay
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      transitionTime,
      delay,
    ]
  }
  static func == (lhs: GenericLevelSet, rhs: GenericLevelSet) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.level, rhs.level) && deepEqualsPigeonGenerated(lhs.transitionTime, rhs.transitionTime) && deepEqualsPigeonGenerated(lhs.delay, rhs.delay)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenericLevelSet")
    deepHashPigeonGenerated(value: level, hasher: &hasher)
    deepHashPigeonGenerated(value: transitionTime, hasher: &hasher)
    deepHashPigeonGenerated(value: delay, hasher: &hasher)
  }
}

private class PigeonGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RxMetadataStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ProvisioningEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MeshNetwork.fromList(self.readValue() as! [Any?])
    case 132:
      return NetworkKey.fromList(self.readValue() as! [Any?])
    case 133:
      return AppKey.fromList(self.readValue() as! [Any?])
    case 134:
      return Provisioner.fromList(self.readValue() as! [Any?])
    case 135:
      return FlutterUnprovisionedDevice.fromList(self.readValue() as! [Any?])
    case 136:
      return ProvisionedNode.fromList(self.readValue() as! [Any?])
    case 137:
      return Element.fromList(self.readValue() as! [Any?])
    case 138:
      return Model.fromList(self.readValue() as! [Any?])
    case 139:
      return Publication.fromList(self.readValue() as! [Any?])
    case 140:
      return MeshGroup.fromList(self.readValue() as! [Any?])
    case 141:
      return MeshMessage.fromList(self.readValue() as! [Any?])
    case 142:
      return RxAccessMessage.fromList(self.readValue() as! [Any?])
    case 143:
      return ProvisioningParameters.fromList(self.readValue() as! [Any?])
    case 144:
      return ProvisioningEvent.fromList(self.readValue() as! [Any?])
    case 145:
      return GenericOnOffSet.fromList(self.readValue() as! [Any?])
    case 146:
      return GenericLevelSet.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RxMetadataStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ProvisioningEventType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MeshNetwork {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NetworkKey {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AppKey {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? Provisioner {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? FlutterUnprovisionedDevice {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisionedNode {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? Element {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? Model {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? Publication {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? MeshGroup {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? MeshMessage {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? RxAccessMessage {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisioningParameters {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisioningEvent {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? GenericOnOffSet {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? GenericLevelSet {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonGeneratedPigeonCodecWriter(data: data)
  }
}

class PigeonGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonGeneratedPigeonCodec(readerWriter: PigeonGeneratedPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MeshApi {
  func createNetwork(name: String) throws -> MeshNetwork
  func loadNetwork() throws -> MeshNetwork
  func saveNetwork() throws -> Bool
  func exportNetwork(path: String) throws -> Bool
  func importNetwork(path: String) throws -> Bool
  func startScan() throws
  func stopScan() throws
  func provisionDevice(device: FlutterUnprovisionedDevice, params: ProvisioningParameters) throws -> ProvisionedNode
  /// Provide user input required by Output OOB (numeric).
  ///
  /// Used when provisioning emits an OOB input request that requires the user to enter a value
  /// shown on the device.
  func provideProvisioningOobNumeric(deviceId: String, value: Int64) throws -> Bool
  /// Provide user input required by Output OOB (alphanumeric).
  func provideProvisioningOobAlphaNumeric(deviceId: String, value: String) throws -> Bool
  func sendMessage(message: MeshMessage) throws
  func getNodes() throws -> [ProvisionedNode]
  func removeNode(nodeId: String) throws
  func createGroup(name: String) throws -> MeshGroup
  func getGroups() throws -> [MeshGroup]
  func addNodeToGroup(nodeId: String, groupId: String) throws
  func createVirtualGroup(name: String, labelUuid: [Int64]) throws -> MeshGroup
  func removeGroup(groupId: String) throws -> Bool
  func addSubscriptionVirtual(elementAddress: Int64, modelId: Int64, labelUuid: [Int64]) throws -> Bool
  func removeSubscriptionVirtual(elementAddress: Int64, modelId: Int64, labelUuid: [Int64]) throws -> Bool
  func setPublicationVirtual(elementAddress: Int64, modelId: Int64, labelUuid: [Int64], appKeyIndex: Int64, ttl: Int64?) throws -> Bool
  /// Fetch Composition Data for a given node and persist it in the Mesh DB.
  ///
  /// - `destination`: the node's unicast address.
  /// - `page`: Composition Data Page (typically 0).
  ///
  /// Returns `true` when the operation completed successfully.
  func fetchCompositionData(destination: Int64, page: Int64) throws -> Bool
  /// Add (or update) an AppKey in the Mesh DB.
  ///
  /// - `appKeyIndex`: 0..4095
  /// - `keyHex`: 16-byte (128-bit) key in hex (32 chars, case-insensitive).
  func addAppKey(appKeyIndex: Int64, keyHex: String) throws -> Bool
  /// Add (or update) a Network Key in the Mesh DB.
  ///
  /// - `netKeyIndex`: 0..4095
  /// - `keyHex`: 16-byte (128-bit) key in hex (32 chars).
  func addNetworkKey(netKeyIndex: Int64, keyHex: String) throws -> Bool
  /// Return the current network keys as seen by the native Mesh DB.
  func getNetworkKeys() throws -> [NetworkKey]
  /// Return the current application keys as seen by the native Mesh DB.
  func getAppKeys() throws -> [AppKey]
  /// Set the Default TTL on a node.
  func setNodeDefaultTtl(destination: Int64, ttl: Int64) throws -> Bool
  /// Enable/disable Relay on a node.
  func setNodeRelay(destination: Int64, enabled: Bool, retransmitCount: Int64, retransmitIntervalMs: Int64) throws -> Bool
  /// Enable/disable GATT Proxy on a node.
  func setNodeGattProxy(destination: Int64, enabled: Bool) throws -> Bool
  /// Enable/disable Friend on a node.
  func setNodeFriend(destination: Int64, enabled: Bool) throws -> Bool
  /// Enable/disable Secure Network Beacon on a node.
  func setNodeBeacon(destination: Int64, enabled: Bool) throws -> Bool
  /// Set Network Transmit parameters on a node.
  func setNodeNetworkTransmit(destination: Int64, count: Int64, intervalMs: Int64) throws -> Bool
  /// Trigger a remote Node Reset.
  func nodeReset(destination: Int64) throws -> Bool
  /// Export a configuration bundle to a file path.
  ///
  /// This is intended to include:
  /// - Standard Mesh DB export (Configuration Database Profile 1.0.1)
  /// - Plugin secure state when applicable (e.g. Android secure properties)
  func exportConfigurationBundle(path: String) throws -> Bool
  /// Import a configuration bundle from a file path.
  func importConfigurationBundle(path: String) throws -> Bool
  /// Remove a network key on a **remote** node (Config NetKey Delete).
  ///
  /// [destination] is the unicast address of the element with the Configuration Server (usually primary).
  func removeNetworkKeyRemote(destination: Int64, netKeyIndex: Int64) throws -> Bool
  /// Remove an application key on a **remote** node (Config App Key Delete).
  ///
  /// [boundNetKeyIndex] is the NetKey that the AppKey is bound to.
  func removeAppKeyRemote(destination: Int64, appKeyIndex: Int64, boundNetKeyIndex: Int64) throws -> Bool
  /// Read Key Refresh phase for [netKeyIndex] on a node (Config Key Refresh Phase Get).
  ///
  /// Returns `0` = normal, `1` = key distribution, `2` = using new keys, or `-1` if unavailable.
  func getKeyRefreshPhase(destination: Int64, netKeyIndex: Int64) throws -> Int64
  /// Set Key Refresh phase transition (Config Key Refresh Phase Set).
  ///
  /// [transition] uses Nordic / Mesh values: `2` = use new keys, `3` = revoke old keys.
  func setKeyRefreshPhaseTransition(destination: Int64, netKeyIndex: Int64, transition: Int64) throws -> Bool
  /// Clears the loaded mesh, persisted plugin storage, and secure state (Android) so the app can
  /// [createNetwork] or [import] a fresh database.
  func resetLocalMeshState() throws -> Bool
  /// Bind an AppKey to a model on a given element address.
  func bindAppKey(elementAddress: Int64, modelId: Int64, appKeyIndex: Int64) throws -> Bool
  /// Unbind an AppKey from a model on a given element address.
  func unbindAppKey(elementAddress: Int64, modelId: Int64, appKeyIndex: Int64) throws -> Bool
  /// Add a subscription address to a model on a given element address.
  func addSubscription(elementAddress: Int64, modelId: Int64, address: Int64) throws -> Bool
  /// Remove a subscription address from a model on a given element address.
  func removeSubscription(elementAddress: Int64, modelId: Int64, address: Int64) throws -> Bool
  /// Set publication for a model on a given element address.
  func setPublication(elementAddress: Int64, modelId: Int64, publishAddress: Int64, appKeyIndex: Int64, ttl: Int64?) throws -> Bool
  func connectProxy(deviceId: String, proxyUnicastAddress: Int64) throws -> Bool
  func disconnectProxy() throws -> Bool
  func isProxyConnected() throws -> Bool
  func connectProvisioning(deviceId: String) throws -> Bool
  func disconnectProvisioning() throws -> Bool
  func isProvisioningConnected() throws -> Bool
  /// Whether the native implementation can reliably populate `MeshMessage.address`
  /// (source address) for incoming Access messages.
  func supportsRxSourceAddress() throws -> Bool
  /// Clear persisted secure mesh state used for stable Access message sending.
  ///
  /// Intended for debugging and recovery (e.g. when switching Mesh DBs).
  func clearSecureStorage() throws
  /// Enable/disable experimental RX metadata extraction on Android.
  ///
  /// When enabled, Android may use internal APIs (via reflection) to extract the
  /// source address for incoming Access messages. When disabled, Android will
  /// use only public APIs and `MeshMessage.address` may be null.
  ///
  /// On iOS this is a no-op.
  func setExperimentalRxMetadataEnabled(enabled: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MeshApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `MeshApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MeshApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createNetworkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          let result = try api.createNetwork(name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createNetworkChannel.setMessageHandler(nil)
    }
    let loadNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.loadNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadNetworkChannel.setMessageHandler { _, reply in
        do {
          let result = try api.loadNetwork()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadNetworkChannel.setMessageHandler(nil)
    }
    let saveNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.saveNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveNetworkChannel.setMessageHandler { _, reply in
        do {
          let result = try api.saveNetwork()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveNetworkChannel.setMessageHandler(nil)
    }
    let exportNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.exportNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportNetworkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.exportNetwork(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exportNetworkChannel.setMessageHandler(nil)
    }
    let importNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.importNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importNetworkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.importNetwork(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      importNetworkChannel.setMessageHandler(nil)
    }
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { _, reply in
        do {
          try api.startScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        do {
          try api.stopScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let provisionDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provisionDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      provisionDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceArg = args[0] as! FlutterUnprovisionedDevice
        let paramsArg = args[1] as! ProvisioningParameters
        do {
          let result = try api.provisionDevice(device: deviceArg, params: paramsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      provisionDeviceChannel.setMessageHandler(nil)
    }
    /// Provide user input required by Output OOB (numeric).
    ///
    /// Used when provisioning emits an OOB input request that requires the user to enter a value
    /// shown on the device.
    let provideProvisioningOobNumericChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provideProvisioningOobNumeric\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      provideProvisioningOobNumericChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let valueArg = args[1] as! Int64
        do {
          let result = try api.provideProvisioningOobNumeric(deviceId: deviceIdArg, value: valueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      provideProvisioningOobNumericChannel.setMessageHandler(nil)
    }
    /// Provide user input required by Output OOB (alphanumeric).
    let provideProvisioningOobAlphaNumericChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provideProvisioningOobAlphaNumeric\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      provideProvisioningOobAlphaNumericChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let valueArg = args[1] as! String
        do {
          let result = try api.provideProvisioningOobAlphaNumeric(deviceId: deviceIdArg, value: valueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      provideProvisioningOobAlphaNumericChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! MeshMessage
        do {
          try api.sendMessage(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let getNodesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getNodes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNodesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNodes()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNodesChannel.setMessageHandler(nil)
    }
    let removeNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.removeNode(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeNodeChannel.setMessageHandler(nil)
    }
    let createGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          let result = try api.createGroup(name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createGroupChannel.setMessageHandler(nil)
    }
    let getGroupsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getGroups\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getGroupsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getGroups()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getGroupsChannel.setMessageHandler(nil)
    }
    let addNodeToGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addNodeToGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addNodeToGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let groupIdArg = args[1] as! String
        do {
          try api.addNodeToGroup(nodeId: nodeIdArg, groupId: groupIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addNodeToGroupChannel.setMessageHandler(nil)
    }
    let createVirtualGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createVirtualGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createVirtualGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let labelUuidArg = args[1] as! [Int64]
        do {
          let result = try api.createVirtualGroup(name: nameArg, labelUuid: labelUuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createVirtualGroupChannel.setMessageHandler(nil)
    }
    let removeGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let groupIdArg = args[0] as! String
        do {
          let result = try api.removeGroup(groupId: groupIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeGroupChannel.setMessageHandler(nil)
    }
    let addSubscriptionVirtualChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addSubscriptionVirtual\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addSubscriptionVirtualChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let labelUuidArg = args[2] as! [Int64]
        do {
          let result = try api.addSubscriptionVirtual(elementAddress: elementAddressArg, modelId: modelIdArg, labelUuid: labelUuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addSubscriptionVirtualChannel.setMessageHandler(nil)
    }
    let removeSubscriptionVirtualChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeSubscriptionVirtual\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeSubscriptionVirtualChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let labelUuidArg = args[2] as! [Int64]
        do {
          let result = try api.removeSubscriptionVirtual(elementAddress: elementAddressArg, modelId: modelIdArg, labelUuid: labelUuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeSubscriptionVirtualChannel.setMessageHandler(nil)
    }
    let setPublicationVirtualChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setPublicationVirtual\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPublicationVirtualChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let labelUuidArg = args[2] as! [Int64]
        let appKeyIndexArg = args[3] as! Int64
        let ttlArg: Int64? = nilOrValue(args[4])
        do {
          let result = try api.setPublicationVirtual(elementAddress: elementAddressArg, modelId: modelIdArg, labelUuid: labelUuidArg, appKeyIndex: appKeyIndexArg, ttl: ttlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPublicationVirtualChannel.setMessageHandler(nil)
    }
    /// Fetch Composition Data for a given node and persist it in the Mesh DB.
    ///
    /// - `destination`: the node's unicast address.
    /// - `page`: Composition Data Page (typically 0).
    ///
    /// Returns `true` when the operation completed successfully.
    let fetchCompositionDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.fetchCompositionData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchCompositionDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let pageArg = args[1] as! Int64
        do {
          let result = try api.fetchCompositionData(destination: destinationArg, page: pageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fetchCompositionDataChannel.setMessageHandler(nil)
    }
    /// Add (or update) an AppKey in the Mesh DB.
    ///
    /// - `appKeyIndex`: 0..4095
    /// - `keyHex`: 16-byte (128-bit) key in hex (32 chars, case-insensitive).
    let addAppKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addAppKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAppKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appKeyIndexArg = args[0] as! Int64
        let keyHexArg = args[1] as! String
        do {
          let result = try api.addAppKey(appKeyIndex: appKeyIndexArg, keyHex: keyHexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAppKeyChannel.setMessageHandler(nil)
    }
    /// Add (or update) a Network Key in the Mesh DB.
    ///
    /// - `netKeyIndex`: 0..4095
    /// - `keyHex`: 16-byte (128-bit) key in hex (32 chars).
    let addNetworkKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addNetworkKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addNetworkKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let netKeyIndexArg = args[0] as! Int64
        let keyHexArg = args[1] as! String
        do {
          let result = try api.addNetworkKey(netKeyIndex: netKeyIndexArg, keyHex: keyHexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addNetworkKeyChannel.setMessageHandler(nil)
    }
    /// Return the current network keys as seen by the native Mesh DB.
    let getNetworkKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getNetworkKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNetworkKeysChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNetworkKeys()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNetworkKeysChannel.setMessageHandler(nil)
    }
    /// Return the current application keys as seen by the native Mesh DB.
    let getAppKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getAppKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppKeysChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAppKeys()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAppKeysChannel.setMessageHandler(nil)
    }
    /// Set the Default TTL on a node.
    let setNodeDefaultTtlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeDefaultTtl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNodeDefaultTtlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let ttlArg = args[1] as! Int64
        do {
          let result = try api.setNodeDefaultTtl(destination: destinationArg, ttl: ttlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNodeDefaultTtlChannel.setMessageHandler(nil)
    }
    /// Enable/disable Relay on a node.
    let setNodeRelayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeRelay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNodeRelayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let enabledArg = args[1] as! Bool
        let retransmitCountArg = args[2] as! Int64
        let retransmitIntervalMsArg = args[3] as! Int64
        do {
          let result = try api.setNodeRelay(destination: destinationArg, enabled: enabledArg, retransmitCount: retransmitCountArg, retransmitIntervalMs: retransmitIntervalMsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNodeRelayChannel.setMessageHandler(nil)
    }
    /// Enable/disable GATT Proxy on a node.
    let setNodeGattProxyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeGattProxy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNodeGattProxyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let enabledArg = args[1] as! Bool
        do {
          let result = try api.setNodeGattProxy(destination: destinationArg, enabled: enabledArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNodeGattProxyChannel.setMessageHandler(nil)
    }
    /// Enable/disable Friend on a node.
    let setNodeFriendChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeFriend\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNodeFriendChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let enabledArg = args[1] as! Bool
        do {
          let result = try api.setNodeFriend(destination: destinationArg, enabled: enabledArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNodeFriendChannel.setMessageHandler(nil)
    }
    /// Enable/disable Secure Network Beacon on a node.
    let setNodeBeaconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeBeacon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNodeBeaconChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let enabledArg = args[1] as! Bool
        do {
          let result = try api.setNodeBeacon(destination: destinationArg, enabled: enabledArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNodeBeaconChannel.setMessageHandler(nil)
    }
    /// Set Network Transmit parameters on a node.
    let setNodeNetworkTransmitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeNetworkTransmit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNodeNetworkTransmitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let countArg = args[1] as! Int64
        let intervalMsArg = args[2] as! Int64
        do {
          let result = try api.setNodeNetworkTransmit(destination: destinationArg, count: countArg, intervalMs: intervalMsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNodeNetworkTransmitChannel.setMessageHandler(nil)
    }
    /// Trigger a remote Node Reset.
    let nodeResetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.nodeReset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      nodeResetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        do {
          let result = try api.nodeReset(destination: destinationArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      nodeResetChannel.setMessageHandler(nil)
    }
    /// Export a configuration bundle to a file path.
    ///
    /// This is intended to include:
    /// - Standard Mesh DB export (Configuration Database Profile 1.0.1)
    /// - Plugin secure state when applicable (e.g. Android secure properties)
    let exportConfigurationBundleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.exportConfigurationBundle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportConfigurationBundleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.exportConfigurationBundle(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exportConfigurationBundleChannel.setMessageHandler(nil)
    }
    /// Import a configuration bundle from a file path.
    let importConfigurationBundleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.importConfigurationBundle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importConfigurationBundleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.importConfigurationBundle(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      importConfigurationBundleChannel.setMessageHandler(nil)
    }
    /// Remove a network key on a **remote** node (Config NetKey Delete).
    ///
    /// [destination] is the unicast address of the element with the Configuration Server (usually primary).
    let removeNetworkKeyRemoteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeNetworkKeyRemote\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeNetworkKeyRemoteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let netKeyIndexArg = args[1] as! Int64
        do {
          let result = try api.removeNetworkKeyRemote(destination: destinationArg, netKeyIndex: netKeyIndexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeNetworkKeyRemoteChannel.setMessageHandler(nil)
    }
    /// Remove an application key on a **remote** node (Config App Key Delete).
    ///
    /// [boundNetKeyIndex] is the NetKey that the AppKey is bound to.
    let removeAppKeyRemoteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeAppKeyRemote\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAppKeyRemoteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let appKeyIndexArg = args[1] as! Int64
        let boundNetKeyIndexArg = args[2] as! Int64
        do {
          let result = try api.removeAppKeyRemote(destination: destinationArg, appKeyIndex: appKeyIndexArg, boundNetKeyIndex: boundNetKeyIndexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeAppKeyRemoteChannel.setMessageHandler(nil)
    }
    /// Read Key Refresh phase for [netKeyIndex] on a node (Config Key Refresh Phase Get).
    ///
    /// Returns `0` = normal, `1` = key distribution, `2` = using new keys, or `-1` if unavailable.
    let getKeyRefreshPhaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getKeyRefreshPhase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getKeyRefreshPhaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let netKeyIndexArg = args[1] as! Int64
        do {
          let result = try api.getKeyRefreshPhase(destination: destinationArg, netKeyIndex: netKeyIndexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getKeyRefreshPhaseChannel.setMessageHandler(nil)
    }
    /// Set Key Refresh phase transition (Config Key Refresh Phase Set).
    ///
    /// [transition] uses Nordic / Mesh values: `2` = use new keys, `3` = revoke old keys.
    let setKeyRefreshPhaseTransitionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setKeyRefreshPhaseTransition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setKeyRefreshPhaseTransitionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationArg = args[0] as! Int64
        let netKeyIndexArg = args[1] as! Int64
        let transitionArg = args[2] as! Int64
        do {
          let result = try api.setKeyRefreshPhaseTransition(destination: destinationArg, netKeyIndex: netKeyIndexArg, transition: transitionArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setKeyRefreshPhaseTransitionChannel.setMessageHandler(nil)
    }
    /// Clears the loaded mesh, persisted plugin storage, and secure state (Android) so the app can
    /// [createNetwork] or [import] a fresh database.
    let resetLocalMeshStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.resetLocalMeshState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetLocalMeshStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.resetLocalMeshState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetLocalMeshStateChannel.setMessageHandler(nil)
    }
    /// Bind an AppKey to a model on a given element address.
    let bindAppKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.bindAppKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bindAppKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let appKeyIndexArg = args[2] as! Int64
        do {
          let result = try api.bindAppKey(elementAddress: elementAddressArg, modelId: modelIdArg, appKeyIndex: appKeyIndexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      bindAppKeyChannel.setMessageHandler(nil)
    }
    /// Unbind an AppKey from a model on a given element address.
    let unbindAppKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.unbindAppKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unbindAppKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let appKeyIndexArg = args[2] as! Int64
        do {
          let result = try api.unbindAppKey(elementAddress: elementAddressArg, modelId: modelIdArg, appKeyIndex: appKeyIndexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unbindAppKeyChannel.setMessageHandler(nil)
    }
    /// Add a subscription address to a model on a given element address.
    let addSubscriptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addSubscription\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addSubscriptionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let addressArg = args[2] as! Int64
        do {
          let result = try api.addSubscription(elementAddress: elementAddressArg, modelId: modelIdArg, address: addressArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addSubscriptionChannel.setMessageHandler(nil)
    }
    /// Remove a subscription address from a model on a given element address.
    let removeSubscriptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeSubscription\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeSubscriptionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let addressArg = args[2] as! Int64
        do {
          let result = try api.removeSubscription(elementAddress: elementAddressArg, modelId: modelIdArg, address: addressArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeSubscriptionChannel.setMessageHandler(nil)
    }
    /// Set publication for a model on a given element address.
    let setPublicationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setPublication\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPublicationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let elementAddressArg = args[0] as! Int64
        let modelIdArg = args[1] as! Int64
        let publishAddressArg = args[2] as! Int64
        let appKeyIndexArg = args[3] as! Int64
        let ttlArg: Int64? = nilOrValue(args[4])
        do {
          let result = try api.setPublication(elementAddress: elementAddressArg, modelId: modelIdArg, publishAddress: publishAddressArg, appKeyIndex: appKeyIndexArg, ttl: ttlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPublicationChannel.setMessageHandler(nil)
    }
    let connectProxyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.connectProxy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectProxyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let proxyUnicastAddressArg = args[1] as! Int64
        do {
          let result = try api.connectProxy(deviceId: deviceIdArg, proxyUnicastAddress: proxyUnicastAddressArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectProxyChannel.setMessageHandler(nil)
    }
    let disconnectProxyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.disconnectProxy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectProxyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.disconnectProxy()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectProxyChannel.setMessageHandler(nil)
    }
    let isProxyConnectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.isProxyConnected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isProxyConnectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isProxyConnected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isProxyConnectedChannel.setMessageHandler(nil)
    }
    let connectProvisioningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.connectProvisioning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectProvisioningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          let result = try api.connectProvisioning(deviceId: deviceIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectProvisioningChannel.setMessageHandler(nil)
    }
    let disconnectProvisioningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.disconnectProvisioning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectProvisioningChannel.setMessageHandler { _, reply in
        do {
          let result = try api.disconnectProvisioning()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectProvisioningChannel.setMessageHandler(nil)
    }
    let isProvisioningConnectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.isProvisioningConnected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isProvisioningConnectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isProvisioningConnected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isProvisioningConnectedChannel.setMessageHandler(nil)
    }
    /// Whether the native implementation can reliably populate `MeshMessage.address`
    /// (source address) for incoming Access messages.
    let supportsRxSourceAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.supportsRxSourceAddress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      supportsRxSourceAddressChannel.setMessageHandler { _, reply in
        do {
          let result = try api.supportsRxSourceAddress()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      supportsRxSourceAddressChannel.setMessageHandler(nil)
    }
    /// Clear persisted secure mesh state used for stable Access message sending.
    ///
    /// Intended for debugging and recovery (e.g. when switching Mesh DBs).
    let clearSecureStorageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.clearSecureStorage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSecureStorageChannel.setMessageHandler { _, reply in
        do {
          try api.clearSecureStorage()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearSecureStorageChannel.setMessageHandler(nil)
    }
    /// Enable/disable experimental RX metadata extraction on Android.
    ///
    /// When enabled, Android may use internal APIs (via reflection) to extract the
    /// source address for incoming Access messages. When disabled, Android will
    /// use only public APIs and `MeshMessage.address` may be null.
    ///
    /// On iOS this is a no-op.
    let setExperimentalRxMetadataEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setExperimentalRxMetadataEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExperimentalRxMetadataEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setExperimentalRxMetadataEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setExperimentalRxMetadataEnabledChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MeshFlutterApiProtocol {
  func onDeviceDiscovered(device deviceArg: FlutterUnprovisionedDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMessageReceived(message messageArg: MeshMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A richer, forward-compatible RX event that carries best-effort metadata.
  ///
  /// This stream is controlled by this plugin's contract (rather than relying on
  /// internal/native library details) so apps can build stable logging and routing.
  func onRxAccessMessage(event eventArg: RxAccessMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Provisioning lifecycle events (progress + OOB prompts).
  func onProvisioningEvent(event eventArg: ProvisioningEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MeshFlutterApi: MeshFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  func onDeviceDiscovered(device deviceArg: FlutterUnprovisionedDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onDeviceDiscovered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMessageReceived(message messageArg: MeshMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onMessageReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A richer, forward-compatible RX event that carries best-effort metadata.
  ///
  /// This stream is controlled by this plugin's contract (rather than relying on
  /// internal/native library details) so apps can build stable logging and routing.
  func onRxAccessMessage(event eventArg: RxAccessMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onRxAccessMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Provisioning lifecycle events (progress + OOB prompts).
  func onProvisioningEvent(event eventArg: ProvisioningEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onProvisioningEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
