// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

@import Foundation;

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class MeshNetwork;
@class NetworkKey;
@class AppKey;
@class Provisioner;
@class UnprovisionedDevice;
@class ProvisionedNode;
@class Element;
@class Model;
@class MeshGroup;
@class MeshMessage;
@class ProvisioningParameters;
@class GenericOnOffSet;
@class GenericLevelSet;

@interface MeshNetwork : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithNetworkId:(NSString *)networkId
    name:(NSString *)name
    networkKeys:(NSArray<NetworkKey *> *)networkKeys
    appKeys:(NSArray<AppKey *> *)appKeys
    nodes:(NSArray<ProvisionedNode *> *)nodes
    groups:(NSArray<MeshGroup *> *)groups
    provisioner:(Provisioner *)provisioner;
@property(nonatomic, copy) NSString * networkId;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy) NSArray<NetworkKey *> * networkKeys;
@property(nonatomic, copy) NSArray<AppKey *> * appKeys;
@property(nonatomic, copy) NSArray<ProvisionedNode *> * nodes;
@property(nonatomic, copy) NSArray<MeshGroup *> * groups;
@property(nonatomic, strong) Provisioner * provisioner;
@end

@interface NetworkKey : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithKeyId:(NSString *)keyId
    key:(NSString *)key
    index:(NSInteger )index
    enabled:(BOOL )enabled;
@property(nonatomic, copy) NSString * keyId;
@property(nonatomic, copy) NSString * key;
@property(nonatomic, assign) NSInteger  index;
@property(nonatomic, assign) BOOL  enabled;
@end

@interface AppKey : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithKeyId:(NSString *)keyId
    key:(NSString *)key
    index:(NSInteger )index
    enabled:(BOOL )enabled;
@property(nonatomic, copy) NSString * keyId;
@property(nonatomic, copy) NSString * key;
@property(nonatomic, assign) NSInteger  index;
@property(nonatomic, assign) BOOL  enabled;
@end

@interface Provisioner : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithName:(NSString *)name
    provisionerId:(NSString *)provisionerId
    addressRange:(NSArray<NSNumber *> *)addressRange;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy) NSString * provisionerId;
@property(nonatomic, copy) NSArray<NSNumber *> * addressRange;
@end

@interface UnprovisionedDevice : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithDeviceId:(NSString *)deviceId
    name:(NSString *)name
    rssi:(NSInteger )rssi
    uuid:(NSArray<NSNumber *> *)uuid;
@property(nonatomic, copy) NSString * deviceId;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, assign) NSInteger  rssi;
@property(nonatomic, copy) NSArray<NSNumber *> * uuid;
@end

@interface ProvisionedNode : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithNodeId:(NSString *)nodeId
    name:(NSString *)name
    unicastAddress:(NSInteger )unicastAddress
    uuid:(NSArray<NSNumber *> *)uuid
    elements:(NSArray<Element *> *)elements
    provisioned:(BOOL )provisioned;
@property(nonatomic, copy) NSString * nodeId;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, assign) NSInteger  unicastAddress;
@property(nonatomic, copy) NSArray<NSNumber *> * uuid;
@property(nonatomic, copy) NSArray<Element *> * elements;
@property(nonatomic, assign) BOOL  provisioned;
@end

@interface Element : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAddress:(NSInteger )address
    models:(NSArray<Model *> *)models;
@property(nonatomic, assign) NSInteger  address;
@property(nonatomic, copy) NSArray<Model *> * models;
@end

@interface Model : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithModelId:(NSInteger )modelId
    modelName:(NSString *)modelName
    publishable:(BOOL )publishable
    subscribable:(BOOL )subscribable;
@property(nonatomic, assign) NSInteger  modelId;
@property(nonatomic, copy) NSString * modelName;
@property(nonatomic, assign) BOOL  publishable;
@property(nonatomic, assign) BOOL  subscribable;
@end

@interface MeshGroup : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithGroupId:(NSString *)groupId
    name:(NSString *)name
    address:(NSInteger )address
    nodeIds:(NSArray<NSString *> *)nodeIds;
@property(nonatomic, copy) NSString * groupId;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, assign) NSInteger  address;
@property(nonatomic, copy) NSArray<NSString *> * nodeIds;
@end

@interface MeshMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithOpcode:(NSInteger )opcode
    address:(NSInteger )address
    appKeyIndex:(NSInteger )appKeyIndex
    parameters:(NSDictionary<NSString *, dynamic *> *)parameters;
@property(nonatomic, assign) NSInteger  opcode;
@property(nonatomic, assign) NSInteger  address;
@property(nonatomic, assign) NSInteger  appKeyIndex;
@property(nonatomic, copy) NSDictionary<NSString *, dynamic *> * parameters;
@end

@interface ProvisioningParameters : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithDeviceName:(NSString *)deviceName
    oobMethod:(nullable NSNumber *)oobMethod
    oobData:(nullable NSString *)oobData
    enablePrivacy:(BOOL )enablePrivacy;
@property(nonatomic, copy) NSString * deviceName;
@property(nonatomic, strong, nullable) NSNumber * oobMethod;
@property(nonatomic, copy, nullable) NSString * oobData;
@property(nonatomic, assign) BOOL  enablePrivacy;
@end

@interface GenericOnOffSet : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithState:(BOOL )state
    transitionTime:(NSInteger )transitionTime
    delay:(NSInteger )delay;
@property(nonatomic, assign) BOOL  state;
@property(nonatomic, assign) NSInteger  transitionTime;
@property(nonatomic, assign) NSInteger  delay;
@end

@interface GenericLevelSet : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLevel:(NSInteger )level
    transitionTime:(NSInteger )transitionTime
    delay:(NSInteger )delay;
@property(nonatomic, assign) NSInteger  level;
@property(nonatomic, assign) NSInteger  transitionTime;
@property(nonatomic, assign) NSInteger  delay;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetPigeonGeneratedCodec(void);

@protocol MeshApi
/// @return `nil` only when `error != nil`.
- (nullable MeshNetwork *)createNetworkName:(NSString *)name error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable MeshNetwork *)loadNetworkWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)saveNetworkWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)exportNetworkPath:(NSString *)path error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)importNetworkPath:(NSString *)path error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startScanWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopScanWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable ProvisionedNode *)provisionDeviceDevice:(UnprovisionedDevice *)device params:(ProvisioningParameters *)params error:(FlutterError *_Nullable *_Nonnull)error;
- (void)sendMessageMessage:(MeshMessage *)message error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<ProvisionedNode *> *)getNodesWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)removeNodeNodeId:(NSString *)nodeId error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable MeshGroup *)createGroupName:(NSString *)name error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<MeshGroup *> *)getGroupsWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)addNodeToGroupNodeId:(NSString *)nodeId groupId:(NSString *)groupId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpMeshApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MeshApi> *_Nullable api);

extern void SetUpMeshApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MeshApi> *_Nullable api, NSString *messageChannelSuffix);


@interface MeshFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onDeviceDiscoveredDevice:(UnprovisionedDevice *)device completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onMessageReceivedMessage:(MeshMessage *)message completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
