// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPigeonGenerated(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPigeonGenerated(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPigeonGenerated(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPigeonGenerated(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPigeonGenerated(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPigeonGenerated(lhsKey, rhsKey) {
          if deepEqualsPigeonGenerated(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPigeonGenerated(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPigeonGenerated(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPigeonGenerated(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPigeonGenerated(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPigeonGenerated(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPigeonGenerated(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPigeonGenerated(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct MeshNetwork: Hashable {
  var networkId: String? = nil
  var name: String? = nil
  var networkKeys: [NetworkKey]? = nil
  var appKeys: [AppKey]? = nil
  var nodes: [ProvisionedNode]? = nil
  var groups: [MeshGroup]? = nil
  var provisioner: Provisioner? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MeshNetwork? {
    let networkId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let networkKeys: [NetworkKey]? = nilOrValue(pigeonVar_list[2])
    let appKeys: [AppKey]? = nilOrValue(pigeonVar_list[3])
    let nodes: [ProvisionedNode]? = nilOrValue(pigeonVar_list[4])
    let groups: [MeshGroup]? = nilOrValue(pigeonVar_list[5])
    let provisioner: Provisioner? = nilOrValue(pigeonVar_list[6])

    return MeshNetwork(
      networkId: networkId,
      name: name,
      networkKeys: networkKeys,
      appKeys: appKeys,
      nodes: nodes,
      groups: groups,
      provisioner: provisioner
    )
  }
  func toList() -> [Any?] {
    return [
      networkId,
      name,
      networkKeys,
      appKeys,
      nodes,
      groups,
      provisioner,
    ]
  }
  static func == (lhs: MeshNetwork, rhs: MeshNetwork) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.networkId, rhs.networkId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.networkKeys, rhs.networkKeys) && deepEqualsPigeonGenerated(lhs.appKeys, rhs.appKeys) && deepEqualsPigeonGenerated(lhs.nodes, rhs.nodes) && deepEqualsPigeonGenerated(lhs.groups, rhs.groups) && deepEqualsPigeonGenerated(lhs.provisioner, rhs.provisioner)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MeshNetwork")
    deepHashPigeonGenerated(value: networkId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: networkKeys, hasher: &hasher)
    deepHashPigeonGenerated(value: appKeys, hasher: &hasher)
    deepHashPigeonGenerated(value: nodes, hasher: &hasher)
    deepHashPigeonGenerated(value: groups, hasher: &hasher)
    deepHashPigeonGenerated(value: provisioner, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NetworkKey: Hashable {
  var keyId: String? = nil
  var key: String? = nil
  var index: Int64? = nil
  var enabled: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NetworkKey? {
    let keyId: String? = nilOrValue(pigeonVar_list[0])
    let key: String? = nilOrValue(pigeonVar_list[1])
    let index: Int64? = nilOrValue(pigeonVar_list[2])
    let enabled: Bool? = nilOrValue(pigeonVar_list[3])

    return NetworkKey(
      keyId: keyId,
      key: key,
      index: index,
      enabled: enabled
    )
  }
  func toList() -> [Any?] {
    return [
      keyId,
      key,
      index,
      enabled,
    ]
  }
  static func == (lhs: NetworkKey, rhs: NetworkKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.keyId, rhs.keyId) && deepEqualsPigeonGenerated(lhs.key, rhs.key) && deepEqualsPigeonGenerated(lhs.index, rhs.index) && deepEqualsPigeonGenerated(lhs.enabled, rhs.enabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NetworkKey")
    deepHashPigeonGenerated(value: keyId, hasher: &hasher)
    deepHashPigeonGenerated(value: key, hasher: &hasher)
    deepHashPigeonGenerated(value: index, hasher: &hasher)
    deepHashPigeonGenerated(value: enabled, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppKey: Hashable {
  var keyId: String? = nil
  var key: String? = nil
  var index: Int64? = nil
  var enabled: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppKey? {
    let keyId: String? = nilOrValue(pigeonVar_list[0])
    let key: String? = nilOrValue(pigeonVar_list[1])
    let index: Int64? = nilOrValue(pigeonVar_list[2])
    let enabled: Bool? = nilOrValue(pigeonVar_list[3])

    return AppKey(
      keyId: keyId,
      key: key,
      index: index,
      enabled: enabled
    )
  }
  func toList() -> [Any?] {
    return [
      keyId,
      key,
      index,
      enabled,
    ]
  }
  static func == (lhs: AppKey, rhs: AppKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.keyId, rhs.keyId) && deepEqualsPigeonGenerated(lhs.key, rhs.key) && deepEqualsPigeonGenerated(lhs.index, rhs.index) && deepEqualsPigeonGenerated(lhs.enabled, rhs.enabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AppKey")
    deepHashPigeonGenerated(value: keyId, hasher: &hasher)
    deepHashPigeonGenerated(value: key, hasher: &hasher)
    deepHashPigeonGenerated(value: index, hasher: &hasher)
    deepHashPigeonGenerated(value: enabled, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Provisioner: Hashable {
  var name: String? = nil
  var provisionerId: String? = nil
  var addressRange: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Provisioner? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let provisionerId: String? = nilOrValue(pigeonVar_list[1])
    let addressRange: [Int64]? = nilOrValue(pigeonVar_list[2])

    return Provisioner(
      name: name,
      provisionerId: provisionerId,
      addressRange: addressRange
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      provisionerId,
      addressRange,
    ]
  }
  static func == (lhs: Provisioner, rhs: Provisioner) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.provisionerId, rhs.provisionerId) && deepEqualsPigeonGenerated(lhs.addressRange, rhs.addressRange)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Provisioner")
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: provisionerId, hasher: &hasher)
    deepHashPigeonGenerated(value: addressRange, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UnprovisionedDevice: Hashable {
  var deviceId: String? = nil
  var name: String? = nil
  var rssi: Int64? = nil
  var uuid: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UnprovisionedDevice? {
    let deviceId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi: Int64? = nilOrValue(pigeonVar_list[2])
    let uuid: [Int64]? = nilOrValue(pigeonVar_list[3])

    return UnprovisionedDevice(
      deviceId: deviceId,
      name: name,
      rssi: rssi,
      uuid: uuid
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      name,
      rssi,
      uuid,
    ]
  }
  static func == (lhs: UnprovisionedDevice, rhs: UnprovisionedDevice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.deviceId, rhs.deviceId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.rssi, rhs.rssi) && deepEqualsPigeonGenerated(lhs.uuid, rhs.uuid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UnprovisionedDevice")
    deepHashPigeonGenerated(value: deviceId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: rssi, hasher: &hasher)
    deepHashPigeonGenerated(value: uuid, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProvisionedNode: Hashable {
  var nodeId: String? = nil
  var name: String? = nil
  var unicastAddress: Int64? = nil
  var uuid: [Int64]? = nil
  var elements: [Element]? = nil
  var provisioned: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisionedNode? {
    let nodeId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let unicastAddress: Int64? = nilOrValue(pigeonVar_list[2])
    let uuid: [Int64]? = nilOrValue(pigeonVar_list[3])
    let elements: [Element]? = nilOrValue(pigeonVar_list[4])
    let provisioned: Bool? = nilOrValue(pigeonVar_list[5])

    return ProvisionedNode(
      nodeId: nodeId,
      name: name,
      unicastAddress: unicastAddress,
      uuid: uuid,
      elements: elements,
      provisioned: provisioned
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      name,
      unicastAddress,
      uuid,
      elements,
      provisioned,
    ]
  }
  static func == (lhs: ProvisionedNode, rhs: ProvisionedNode) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.nodeId, rhs.nodeId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.unicastAddress, rhs.unicastAddress) && deepEqualsPigeonGenerated(lhs.uuid, rhs.uuid) && deepEqualsPigeonGenerated(lhs.elements, rhs.elements) && deepEqualsPigeonGenerated(lhs.provisioned, rhs.provisioned)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisionedNode")
    deepHashPigeonGenerated(value: nodeId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: unicastAddress, hasher: &hasher)
    deepHashPigeonGenerated(value: uuid, hasher: &hasher)
    deepHashPigeonGenerated(value: elements, hasher: &hasher)
    deepHashPigeonGenerated(value: provisioned, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Element: Hashable {
  var address: Int64? = nil
  var models: [Model]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Element? {
    let address: Int64? = nilOrValue(pigeonVar_list[0])
    let models: [Model]? = nilOrValue(pigeonVar_list[1])

    return Element(
      address: address,
      models: models
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      models,
    ]
  }
  static func == (lhs: Element, rhs: Element) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.address, rhs.address) && deepEqualsPigeonGenerated(lhs.models, rhs.models)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Element")
    deepHashPigeonGenerated(value: address, hasher: &hasher)
    deepHashPigeonGenerated(value: models, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Model: Hashable {
  var modelId: Int64? = nil
  var modelName: String? = nil
  var publishable: Bool? = nil
  var subscribable: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Model? {
    let modelId: Int64? = nilOrValue(pigeonVar_list[0])
    let modelName: String? = nilOrValue(pigeonVar_list[1])
    let publishable: Bool? = nilOrValue(pigeonVar_list[2])
    let subscribable: Bool? = nilOrValue(pigeonVar_list[3])

    return Model(
      modelId: modelId,
      modelName: modelName,
      publishable: publishable,
      subscribable: subscribable
    )
  }
  func toList() -> [Any?] {
    return [
      modelId,
      modelName,
      publishable,
      subscribable,
    ]
  }
  static func == (lhs: Model, rhs: Model) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.modelId, rhs.modelId) && deepEqualsPigeonGenerated(lhs.modelName, rhs.modelName) && deepEqualsPigeonGenerated(lhs.publishable, rhs.publishable) && deepEqualsPigeonGenerated(lhs.subscribable, rhs.subscribable)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Model")
    deepHashPigeonGenerated(value: modelId, hasher: &hasher)
    deepHashPigeonGenerated(value: modelName, hasher: &hasher)
    deepHashPigeonGenerated(value: publishable, hasher: &hasher)
    deepHashPigeonGenerated(value: subscribable, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MeshGroup: Hashable {
  var groupId: String? = nil
  var name: String? = nil
  var address: Int64? = nil
  var nodeIds: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MeshGroup? {
    let groupId: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let address: Int64? = nilOrValue(pigeonVar_list[2])
    let nodeIds: [String]? = nilOrValue(pigeonVar_list[3])

    return MeshGroup(
      groupId: groupId,
      name: name,
      address: address,
      nodeIds: nodeIds
    )
  }
  func toList() -> [Any?] {
    return [
      groupId,
      name,
      address,
      nodeIds,
    ]
  }
  static func == (lhs: MeshGroup, rhs: MeshGroup) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.groupId, rhs.groupId) && deepEqualsPigeonGenerated(lhs.name, rhs.name) && deepEqualsPigeonGenerated(lhs.address, rhs.address) && deepEqualsPigeonGenerated(lhs.nodeIds, rhs.nodeIds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MeshGroup")
    deepHashPigeonGenerated(value: groupId, hasher: &hasher)
    deepHashPigeonGenerated(value: name, hasher: &hasher)
    deepHashPigeonGenerated(value: address, hasher: &hasher)
    deepHashPigeonGenerated(value: nodeIds, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MeshMessage: Hashable {
  var opcode: Int64? = nil
  var address: Int64? = nil
  var appKeyIndex: Int64? = nil
  var parameters: [String: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MeshMessage? {
    let opcode: Int64? = nilOrValue(pigeonVar_list[0])
    let address: Int64? = nilOrValue(pigeonVar_list[1])
    let appKeyIndex: Int64? = nilOrValue(pigeonVar_list[2])
    let parameters: [String: Any?]? = nilOrValue(pigeonVar_list[3])

    return MeshMessage(
      opcode: opcode,
      address: address,
      appKeyIndex: appKeyIndex,
      parameters: parameters
    )
  }
  func toList() -> [Any?] {
    return [
      opcode,
      address,
      appKeyIndex,
      parameters,
    ]
  }
  static func == (lhs: MeshMessage, rhs: MeshMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.opcode, rhs.opcode) && deepEqualsPigeonGenerated(lhs.address, rhs.address) && deepEqualsPigeonGenerated(lhs.appKeyIndex, rhs.appKeyIndex) && deepEqualsPigeonGenerated(lhs.parameters, rhs.parameters)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MeshMessage")
    deepHashPigeonGenerated(value: opcode, hasher: &hasher)
    deepHashPigeonGenerated(value: address, hasher: &hasher)
    deepHashPigeonGenerated(value: appKeyIndex, hasher: &hasher)
    deepHashPigeonGenerated(value: parameters, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProvisioningParameters: Hashable {
  var deviceName: String? = nil
  var oobMethod: Int64? = nil
  var oobData: String? = nil
  var enablePrivacy: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProvisioningParameters? {
    let deviceName: String? = nilOrValue(pigeonVar_list[0])
    let oobMethod: Int64? = nilOrValue(pigeonVar_list[1])
    let oobData: String? = nilOrValue(pigeonVar_list[2])
    let enablePrivacy: Bool? = nilOrValue(pigeonVar_list[3])

    return ProvisioningParameters(
      deviceName: deviceName,
      oobMethod: oobMethod,
      oobData: oobData,
      enablePrivacy: enablePrivacy
    )
  }
  func toList() -> [Any?] {
    return [
      deviceName,
      oobMethod,
      oobData,
      enablePrivacy,
    ]
  }
  static func == (lhs: ProvisioningParameters, rhs: ProvisioningParameters) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.deviceName, rhs.deviceName) && deepEqualsPigeonGenerated(lhs.oobMethod, rhs.oobMethod) && deepEqualsPigeonGenerated(lhs.oobData, rhs.oobData) && deepEqualsPigeonGenerated(lhs.enablePrivacy, rhs.enablePrivacy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProvisioningParameters")
    deepHashPigeonGenerated(value: deviceName, hasher: &hasher)
    deepHashPigeonGenerated(value: oobMethod, hasher: &hasher)
    deepHashPigeonGenerated(value: oobData, hasher: &hasher)
    deepHashPigeonGenerated(value: enablePrivacy, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GenericOnOffSet: Hashable {
  var state: Bool? = nil
  var transitionTime: Int64? = nil
  var delay: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenericOnOffSet? {
    let state: Bool? = nilOrValue(pigeonVar_list[0])
    let transitionTime: Int64? = nilOrValue(pigeonVar_list[1])
    let delay: Int64? = nilOrValue(pigeonVar_list[2])

    return GenericOnOffSet(
      state: state,
      transitionTime: transitionTime,
      delay: delay
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      transitionTime,
      delay,
    ]
  }
  static func == (lhs: GenericOnOffSet, rhs: GenericOnOffSet) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.state, rhs.state) && deepEqualsPigeonGenerated(lhs.transitionTime, rhs.transitionTime) && deepEqualsPigeonGenerated(lhs.delay, rhs.delay)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenericOnOffSet")
    deepHashPigeonGenerated(value: state, hasher: &hasher)
    deepHashPigeonGenerated(value: transitionTime, hasher: &hasher)
    deepHashPigeonGenerated(value: delay, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GenericLevelSet: Hashable {
  var level: Int64? = nil
  var transitionTime: Int64? = nil
  var delay: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenericLevelSet? {
    let level: Int64? = nilOrValue(pigeonVar_list[0])
    let transitionTime: Int64? = nilOrValue(pigeonVar_list[1])
    let delay: Int64? = nilOrValue(pigeonVar_list[2])

    return GenericLevelSet(
      level: level,
      transitionTime: transitionTime,
      delay: delay
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      transitionTime,
      delay,
    ]
  }
  static func == (lhs: GenericLevelSet, rhs: GenericLevelSet) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPigeonGenerated(lhs.level, rhs.level) && deepEqualsPigeonGenerated(lhs.transitionTime, rhs.transitionTime) && deepEqualsPigeonGenerated(lhs.delay, rhs.delay)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenericLevelSet")
    deepHashPigeonGenerated(value: level, hasher: &hasher)
    deepHashPigeonGenerated(value: transitionTime, hasher: &hasher)
    deepHashPigeonGenerated(value: delay, hasher: &hasher)
  }
}

private class PigeonGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MeshNetwork.fromList(self.readValue() as! [Any?])
    case 130:
      return NetworkKey.fromList(self.readValue() as! [Any?])
    case 131:
      return AppKey.fromList(self.readValue() as! [Any?])
    case 132:
      return Provisioner.fromList(self.readValue() as! [Any?])
    case 133:
      return UnprovisionedDevice.fromList(self.readValue() as! [Any?])
    case 134:
      return ProvisionedNode.fromList(self.readValue() as! [Any?])
    case 135:
      return Element.fromList(self.readValue() as! [Any?])
    case 136:
      return Model.fromList(self.readValue() as! [Any?])
    case 137:
      return MeshGroup.fromList(self.readValue() as! [Any?])
    case 138:
      return MeshMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return ProvisioningParameters.fromList(self.readValue() as! [Any?])
    case 140:
      return GenericOnOffSet.fromList(self.readValue() as! [Any?])
    case 141:
      return GenericLevelSet.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MeshNetwork {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NetworkKey {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AppKey {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? Provisioner {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? UnprovisionedDevice {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisionedNode {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? Element {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? Model {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? MeshGroup {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? MeshMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ProvisioningParameters {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? GenericOnOffSet {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? GenericLevelSet {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonGeneratedPigeonCodecWriter(data: data)
  }
}

class PigeonGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonGeneratedPigeonCodec(readerWriter: PigeonGeneratedPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MeshApi {
  func createNetwork(name: String) throws -> MeshNetwork
  func loadNetwork() throws -> MeshNetwork
  func saveNetwork() throws -> Bool
  func exportNetwork(path: String) throws -> Bool
  func importNetwork(path: String) throws -> Bool
  func startScan() throws
  func stopScan() throws
  func provisionDevice(device: UnprovisionedDevice, params: ProvisioningParameters) throws -> ProvisionedNode
  func sendMessage(message: MeshMessage) throws
  func getNodes() throws -> [ProvisionedNode]
  func removeNode(nodeId: String) throws
  func createGroup(name: String) throws -> MeshGroup
  func getGroups() throws -> [MeshGroup]
  func addNodeToGroup(nodeId: String, groupId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MeshApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `MeshApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MeshApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.createNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createNetworkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          let result = try api.createNetwork(name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createNetworkChannel.setMessageHandler(nil)
    }
    let loadNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.loadNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadNetworkChannel.setMessageHandler { _, reply in
        do {
          let result = try api.loadNetwork()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadNetworkChannel.setMessageHandler(nil)
    }
    let saveNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.saveNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveNetworkChannel.setMessageHandler { _, reply in
        do {
          let result = try api.saveNetwork()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveNetworkChannel.setMessageHandler(nil)
    }
    let exportNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.exportNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportNetworkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.exportNetwork(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exportNetworkChannel.setMessageHandler(nil)
    }
    let importNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.importNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importNetworkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.importNetwork(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      importNetworkChannel.setMessageHandler(nil)
    }
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { _, reply in
        do {
          try api.startScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        do {
          try api.stopScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let provisionDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.provisionDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      provisionDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceArg = args[0] as! UnprovisionedDevice
        let paramsArg = args[1] as! ProvisioningParameters
        do {
          let result = try api.provisionDevice(device: deviceArg, params: paramsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      provisionDeviceChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! MeshMessage
        do {
          try api.sendMessage(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let getNodesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.getNodes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNodesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNodes()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNodesChannel.setMessageHandler(nil)
    }
    let removeNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.removeNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.removeNode(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeNodeChannel.setMessageHandler(nil)
    }
    let createGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.createGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          let result = try api.createGroup(name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createGroupChannel.setMessageHandler(nil)
    }
    let getGroupsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.getGroups\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getGroupsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getGroups()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getGroupsChannel.setMessageHandler(nil)
    }
    let addNodeToGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.platojobs_nrf_mesh.MeshApi.addNodeToGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addNodeToGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let groupIdArg = args[1] as! String
        do {
          try api.addNodeToGroup(nodeId: nodeIdArg, groupId: groupIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addNodeToGroupChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MeshFlutterApiProtocol {
  func onDeviceDiscovered(device deviceArg: UnprovisionedDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMessageReceived(message messageArg: MeshMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MeshFlutterApi: MeshFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  func onDeviceDiscovered(device deviceArg: UnprovisionedDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.platojobs_nrf_mesh.MeshFlutterApi.onDeviceDiscovered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMessageReceived(message messageArg: MeshMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.platojobs_nrf_mesh.MeshFlutterApi.onMessageReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
