// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum RxMetadataStatus {
  available,
  unavailable,
}

enum ProvisioningEventType {
  started,
  capabilitiesReceived,
  oobInputRequested,
  oobOutputRequested,
  provisioningCompleted,
  failed,
}

class MeshNetwork {
  MeshNetwork({
    this.networkId,
    this.name,
    this.networkKeys,
    this.appKeys,
    this.nodes,
    this.groups,
    this.provisioner,
  });

  String? networkId;

  String? name;

  List<NetworkKey>? networkKeys;

  List<AppKey>? appKeys;

  List<ProvisionedNode>? nodes;

  List<MeshGroup>? groups;

  Provisioner? provisioner;

  List<Object?> _toList() {
    return <Object?>[
      networkId,
      name,
      networkKeys,
      appKeys,
      nodes,
      groups,
      provisioner,
    ];
  }

  Object encode() {
    return _toList();  }

  static MeshNetwork decode(Object result) {
    result as List<Object?>;
    return MeshNetwork(
      networkId: result[0] as String?,
      name: result[1] as String?,
      networkKeys: (result[2] as List<Object?>?)?.cast<NetworkKey>(),
      appKeys: (result[3] as List<Object?>?)?.cast<AppKey>(),
      nodes: (result[4] as List<Object?>?)?.cast<ProvisionedNode>(),
      groups: (result[5] as List<Object?>?)?.cast<MeshGroup>(),
      provisioner: result[6] as Provisioner?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MeshNetwork || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(networkId, other.networkId) && _deepEquals(name, other.name) && _deepEquals(networkKeys, other.networkKeys) && _deepEquals(appKeys, other.appKeys) && _deepEquals(nodes, other.nodes) && _deepEquals(groups, other.groups) && _deepEquals(provisioner, other.provisioner);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NetworkKey {
  NetworkKey({
    this.keyId,
    this.key,
    this.index,
    this.enabled,
  });

  String? keyId;

  String? key;

  int? index;

  bool? enabled;

  List<Object?> _toList() {
    return <Object?>[
      keyId,
      key,
      index,
      enabled,
    ];
  }

  Object encode() {
    return _toList();  }

  static NetworkKey decode(Object result) {
    result as List<Object?>;
    return NetworkKey(
      keyId: result[0] as String?,
      key: result[1] as String?,
      index: result[2] as int?,
      enabled: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NetworkKey || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyId, other.keyId) && _deepEquals(key, other.key) && _deepEquals(index, other.index) && _deepEquals(enabled, other.enabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AppKey {
  AppKey({
    this.keyId,
    this.key,
    this.index,
    this.enabled,
  });

  String? keyId;

  String? key;

  int? index;

  bool? enabled;

  List<Object?> _toList() {
    return <Object?>[
      keyId,
      key,
      index,
      enabled,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppKey decode(Object result) {
    result as List<Object?>;
    return AppKey(
      keyId: result[0] as String?,
      key: result[1] as String?,
      index: result[2] as int?,
      enabled: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppKey || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyId, other.keyId) && _deepEquals(key, other.key) && _deepEquals(index, other.index) && _deepEquals(enabled, other.enabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class Provisioner {
  Provisioner({
    this.name,
    this.provisionerId,
    this.addressRange,
  });

  String? name;

  String? provisionerId;

  List<int>? addressRange;

  List<Object?> _toList() {
    return <Object?>[
      name,
      provisionerId,
      addressRange,
    ];
  }

  Object encode() {
    return _toList();  }

  static Provisioner decode(Object result) {
    result as List<Object?>;
    return Provisioner(
      name: result[0] as String?,
      provisionerId: result[1] as String?,
      addressRange: (result[2] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Provisioner || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(provisionerId, other.provisionerId) && _deepEquals(addressRange, other.addressRange);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Pigeon transport model for unprovisioned devices.
///
/// Named to avoid clashing with Nordic iOS library types.
class FlutterUnprovisionedDevice {
  FlutterUnprovisionedDevice({
    this.deviceId,
    this.name,
    this.rssi,
    this.uuid,
    this.serviceUuid,
  });

  String? deviceId;

  String? name;

  int? rssi;

  List<int>? uuid;

  String? serviceUuid;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      name,
      rssi,
      uuid,
      serviceUuid,
    ];
  }

  Object encode() {
    return _toList();  }

  static FlutterUnprovisionedDevice decode(Object result) {
    result as List<Object?>;
    return FlutterUnprovisionedDevice(
      deviceId: result[0] as String?,
      name: result[1] as String?,
      rssi: result[2] as int?,
      uuid: (result[3] as List<Object?>?)?.cast<int>(),
      serviceUuid: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FlutterUnprovisionedDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(name, other.name) && _deepEquals(rssi, other.rssi) && _deepEquals(uuid, other.uuid) && _deepEquals(serviceUuid, other.serviceUuid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProvisionedNode {
  ProvisionedNode({
    this.nodeId,
    this.name,
    this.unicastAddress,
    this.uuid,
    this.elements,
    this.provisioned,
  });

  String? nodeId;

  String? name;

  int? unicastAddress;

  List<int>? uuid;

  List<Element>? elements;

  bool? provisioned;

  List<Object?> _toList() {
    return <Object?>[
      nodeId,
      name,
      unicastAddress,
      uuid,
      elements,
      provisioned,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProvisionedNode decode(Object result) {
    result as List<Object?>;
    return ProvisionedNode(
      nodeId: result[0] as String?,
      name: result[1] as String?,
      unicastAddress: result[2] as int?,
      uuid: (result[3] as List<Object?>?)?.cast<int>(),
      elements: (result[4] as List<Object?>?)?.cast<Element>(),
      provisioned: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProvisionedNode || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(nodeId, other.nodeId) && _deepEquals(name, other.name) && _deepEquals(unicastAddress, other.unicastAddress) && _deepEquals(uuid, other.uuid) && _deepEquals(elements, other.elements) && _deepEquals(provisioned, other.provisioned);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class Element {
  Element({
    this.address,
    this.models,
  });

  int? address;

  List<Model>? models;

  List<Object?> _toList() {
    return <Object?>[
      address,
      models,
    ];
  }

  Object encode() {
    return _toList();  }

  static Element decode(Object result) {
    result as List<Object?>;
    return Element(
      address: result[0] as int?,
      models: (result[1] as List<Object?>?)?.cast<Model>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Element || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) && _deepEquals(models, other.models);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class Model {
  Model({
    this.modelId,
    this.modelName,
    this.publishable,
    this.subscribable,
    this.boundAppKeyIndexes,
    this.subscriptions,
    this.publication,
  });

  int? modelId;

  String? modelName;

  bool? publishable;

  bool? subscribable;

  List<int>? boundAppKeyIndexes;

  List<int>? subscriptions;

  Publication? publication;

  List<Object?> _toList() {
    return <Object?>[
      modelId,
      modelName,
      publishable,
      subscribable,
      boundAppKeyIndexes,
      subscriptions,
      publication,
    ];
  }

  Object encode() {
    return _toList();  }

  static Model decode(Object result) {
    result as List<Object?>;
    return Model(
      modelId: result[0] as int?,
      modelName: result[1] as String?,
      publishable: result[2] as bool?,
      subscribable: result[3] as bool?,
      boundAppKeyIndexes: (result[4] as List<Object?>?)?.cast<int>(),
      subscriptions: (result[5] as List<Object?>?)?.cast<int>(),
      publication: result[6] as Publication?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Model || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(modelId, other.modelId) && _deepEquals(modelName, other.modelName) && _deepEquals(publishable, other.publishable) && _deepEquals(subscribable, other.subscribable) && _deepEquals(boundAppKeyIndexes, other.boundAppKeyIndexes) && _deepEquals(subscriptions, other.subscriptions) && _deepEquals(publication, other.publication);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class Publication {
  Publication({
    this.address,
    this.appKeyIndex,
    this.ttl,
  });

  int? address;

  int? appKeyIndex;

  int? ttl;

  List<Object?> _toList() {
    return <Object?>[
      address,
      appKeyIndex,
      ttl,
    ];
  }

  Object encode() {
    return _toList();  }

  static Publication decode(Object result) {
    result as List<Object?>;
    return Publication(
      address: result[0] as int?,
      appKeyIndex: result[1] as int?,
      ttl: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Publication || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) && _deepEquals(appKeyIndex, other.appKeyIndex) && _deepEquals(ttl, other.ttl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MeshGroup {
  MeshGroup({
    this.groupId,
    this.name,
    this.address,
    this.nodeIds,
  });

  String? groupId;

  String? name;

  int? address;

  List<String>? nodeIds;

  List<Object?> _toList() {
    return <Object?>[
      groupId,
      name,
      address,
      nodeIds,
    ];
  }

  Object encode() {
    return _toList();  }

  static MeshGroup decode(Object result) {
    result as List<Object?>;
    return MeshGroup(
      groupId: result[0] as String?,
      name: result[1] as String?,
      address: result[2] as int?,
      nodeIds: (result[3] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MeshGroup || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(groupId, other.groupId) && _deepEquals(name, other.name) && _deepEquals(address, other.address) && _deepEquals(nodeIds, other.nodeIds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MeshMessage {
  MeshMessage({
    this.opcode,
    this.address,
    this.appKeyIndex,
    this.parameters,
  });

  int? opcode;

  int? address;

  int? appKeyIndex;

  Map<String, Object?>? parameters;

  List<Object?> _toList() {
    return <Object?>[
      opcode,
      address,
      appKeyIndex,
      parameters,
    ];
  }

  Object encode() {
    return _toList();  }

  static MeshMessage decode(Object result) {
    result as List<Object?>;
    return MeshMessage(
      opcode: result[0] as int?,
      address: result[1] as int?,
      appKeyIndex: result[2] as int?,
      parameters: (result[3] as Map<Object?, Object?>?)?.cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MeshMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(opcode, other.opcode) && _deepEquals(address, other.address) && _deepEquals(appKeyIndex, other.appKeyIndex) && _deepEquals(parameters, other.parameters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class RxAccessMessage {
  RxAccessMessage({
    this.opcode,
    this.parameters,
    this.source,
    this.destination,
    this.metadataStatus,
  });

  int? opcode;

  /// Access message parameters (raw bytes).
  List<int>? parameters;

  /// Best-effort source address (unicast), if available.
  int? source;

  /// Best-effort destination address, if available.
  int? destination;

  RxMetadataStatus? metadataStatus;

  List<Object?> _toList() {
    return <Object?>[
      opcode,
      parameters,
      source,
      destination,
      metadataStatus,
    ];
  }

  Object encode() {
    return _toList();  }

  static RxAccessMessage decode(Object result) {
    result as List<Object?>;
    return RxAccessMessage(
      opcode: result[0] as int?,
      parameters: (result[1] as List<Object?>?)?.cast<int>(),
      source: result[2] as int?,
      destination: result[3] as int?,
      metadataStatus: result[4] as RxMetadataStatus?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RxAccessMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(opcode, other.opcode) && _deepEquals(parameters, other.parameters) && _deepEquals(source, other.source) && _deepEquals(destination, other.destination) && _deepEquals(metadataStatus, other.metadataStatus);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProvisioningParameters {
  ProvisioningParameters({
    this.deviceName,
    this.oobMethod,
    this.oobData,
    this.enablePrivacy,
  });

  String? deviceName;

  int? oobMethod;

  String? oobData;

  bool? enablePrivacy;

  List<Object?> _toList() {
    return <Object?>[
      deviceName,
      oobMethod,
      oobData,
      enablePrivacy,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProvisioningParameters decode(Object result) {
    result as List<Object?>;
    return ProvisioningParameters(
      deviceName: result[0] as String?,
      oobMethod: result[1] as int?,
      oobData: result[2] as String?,
      enablePrivacy: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProvisioningParameters || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceName, other.deviceName) && _deepEquals(oobMethod, other.oobMethod) && _deepEquals(oobData, other.oobData) && _deepEquals(enablePrivacy, other.enablePrivacy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProvisioningEvent {
  ProvisioningEvent({
    this.deviceId,
    this.type,
    this.message,
    this.progress,
    this.attentionTimer,
  });

  String? deviceId;

  ProvisioningEventType? type;

  String? message;

  int? progress;

  int? attentionTimer;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      type,
      message,
      progress,
      attentionTimer,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProvisioningEvent decode(Object result) {
    result as List<Object?>;
    return ProvisioningEvent(
      deviceId: result[0] as String?,
      type: result[1] as ProvisioningEventType?,
      message: result[2] as String?,
      progress: result[3] as int?,
      attentionTimer: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProvisioningEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(type, other.type) && _deepEquals(message, other.message) && _deepEquals(progress, other.progress) && _deepEquals(attentionTimer, other.attentionTimer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GenericOnOffSet {
  GenericOnOffSet({
    this.state,
    this.transitionTime,
    this.delay,
  });

  bool? state;

  int? transitionTime;

  int? delay;

  List<Object?> _toList() {
    return <Object?>[
      state,
      transitionTime,
      delay,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenericOnOffSet decode(Object result) {
    result as List<Object?>;
    return GenericOnOffSet(
      state: result[0] as bool?,
      transitionTime: result[1] as int?,
      delay: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenericOnOffSet || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(transitionTime, other.transitionTime) && _deepEquals(delay, other.delay);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GenericLevelSet {
  GenericLevelSet({
    this.level,
    this.transitionTime,
    this.delay,
  });

  int? level;

  int? transitionTime;

  int? delay;

  List<Object?> _toList() {
    return <Object?>[
      level,
      transitionTime,
      delay,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenericLevelSet decode(Object result) {
    result as List<Object?>;
    return GenericLevelSet(
      level: result[0] as int?,
      transitionTime: result[1] as int?,
      delay: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenericLevelSet || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(level, other.level) && _deepEquals(transitionTime, other.transitionTime) && _deepEquals(delay, other.delay);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RxMetadataStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ProvisioningEventType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is MeshNetwork) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NetworkKey) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AppKey) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is Provisioner) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is FlutterUnprovisionedDevice) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is ProvisionedNode) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is Element) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is Model) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is Publication) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is MeshGroup) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is MeshMessage) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is RxAccessMessage) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is ProvisioningParameters) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is ProvisioningEvent) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is GenericOnOffSet) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is GenericLevelSet) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RxMetadataStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ProvisioningEventType.values[value];
      case 131:
        return MeshNetwork.decode(readValue(buffer)!);
      case 132:
        return NetworkKey.decode(readValue(buffer)!);
      case 133:
        return AppKey.decode(readValue(buffer)!);
      case 134:
        return Provisioner.decode(readValue(buffer)!);
      case 135:
        return FlutterUnprovisionedDevice.decode(readValue(buffer)!);
      case 136:
        return ProvisionedNode.decode(readValue(buffer)!);
      case 137:
        return Element.decode(readValue(buffer)!);
      case 138:
        return Model.decode(readValue(buffer)!);
      case 139:
        return Publication.decode(readValue(buffer)!);
      case 140:
        return MeshGroup.decode(readValue(buffer)!);
      case 141:
        return MeshMessage.decode(readValue(buffer)!);
      case 142:
        return RxAccessMessage.decode(readValue(buffer)!);
      case 143:
        return ProvisioningParameters.decode(readValue(buffer)!);
      case 144:
        return ProvisioningEvent.decode(readValue(buffer)!);
      case 145:
        return GenericOnOffSet.decode(readValue(buffer)!);
      case 146:
        return GenericLevelSet.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MeshApi {
  /// Constructor for [MeshApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MeshApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<MeshNetwork> createNetwork(String name) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MeshNetwork;
  }

  Future<MeshNetwork> loadNetwork() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.loadNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MeshNetwork;
  }

  Future<bool> saveNetwork() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.saveNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> exportNetwork(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.exportNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> importNetwork(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.importNetwork$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<ProvisionedNode> provisionDevice(FlutterUnprovisionedDevice device, ProvisioningParameters params) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provisionDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[device, params]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ProvisionedNode;
  }

  /// Provide user input required by Output OOB (numeric).
  ///
  /// Used when provisioning emits an OOB input request that requires the user to enter a value
  /// shown on the device.
  Future<bool> provideProvisioningOobNumeric(String deviceId, int value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provideProvisioningOobNumeric$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Provide user input required by Output OOB (alphanumeric).
  Future<bool> provideProvisioningOobAlphaNumeric(String deviceId, String value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provideProvisioningOobAlphaNumeric$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> sendMessage(MeshMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.sendMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<ProvisionedNode>> getNodes() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getNodes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ProvisionedNode>();
  }

  Future<void> removeNode(String nodeId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeNode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[nodeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<MeshGroup> createGroup(String name) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createGroup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MeshGroup;
  }

  Future<List<MeshGroup>> getGroups() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getGroups$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<MeshGroup>();
  }

  Future<void> addNodeToGroup(String nodeId, String groupId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addNodeToGroup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[nodeId, groupId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Fetch Composition Data for a given node and persist it in the Mesh DB.
  ///
  /// - `destination`: the node's unicast address.
  /// - `page`: Composition Data Page (typically 0).
  ///
  /// Returns `true` when the operation completed successfully.
  Future<bool> fetchCompositionData(int destination, {int page = 0}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.fetchCompositionData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination, page]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Add (or update) an AppKey in the Mesh DB.
  ///
  /// - `appKeyIndex`: 0..4095
  /// - `keyHex`: 16-byte (128-bit) key in hex (32 chars, case-insensitive).
  Future<bool> addAppKey(int appKeyIndex, String keyHex) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addAppKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[appKeyIndex, keyHex]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Add (or update) a Network Key in the Mesh DB.
  ///
  /// - `netKeyIndex`: 0..4095
  /// - `keyHex`: 16-byte (128-bit) key in hex (32 chars).
  Future<bool> addNetworkKey(int netKeyIndex, String keyHex) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addNetworkKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[netKeyIndex, keyHex]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Return the current network keys as seen by the native Mesh DB.
  Future<List<NetworkKey>> getNetworkKeys() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getNetworkKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NetworkKey>();
  }

  /// Return the current application keys as seen by the native Mesh DB.
  Future<List<AppKey>> getAppKeys() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getAppKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<AppKey>();
  }

  /// Set the Default TTL on a node.
  Future<bool> setNodeDefaultTtl(int destination, int ttl) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeDefaultTtl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination, ttl]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Enable/disable Relay on a node.
  Future<bool> setNodeRelay(int destination, bool enabled, int retransmitCount, int retransmitIntervalMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeRelay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination, enabled, retransmitCount, retransmitIntervalMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Enable/disable GATT Proxy on a node.
  Future<bool> setNodeGattProxy(int destination, bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeGattProxy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination, enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Enable/disable Friend on a node.
  Future<bool> setNodeFriend(int destination, bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeFriend$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination, enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Enable/disable Secure Network Beacon on a node.
  Future<bool> setNodeBeacon(int destination, bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeBeacon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination, enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Set Network Transmit parameters on a node.
  Future<bool> setNodeNetworkTransmit(int destination, int count, int intervalMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setNodeNetworkTransmit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination, count, intervalMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Trigger a remote Node Reset.
  Future<bool> nodeReset(int destination) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.nodeReset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[destination]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Export a configuration bundle to a file path.
  ///
  /// This is intended to include:
  /// - Standard Mesh DB export (Configuration Database Profile 1.0.1)
  /// - Plugin secure state when applicable (e.g. Android secure properties)
  Future<bool> exportConfigurationBundle(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.exportConfigurationBundle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Import a configuration bundle from a file path.
  Future<bool> importConfigurationBundle(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.importConfigurationBundle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Bind an AppKey to a model on a given element address.
  Future<bool> bindAppKey(int elementAddress, int modelId, int appKeyIndex) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.bindAppKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[elementAddress, modelId, appKeyIndex]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Unbind an AppKey from a model on a given element address.
  Future<bool> unbindAppKey(int elementAddress, int modelId, int appKeyIndex) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.unbindAppKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[elementAddress, modelId, appKeyIndex]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Add a subscription address to a model on a given element address.
  Future<bool> addSubscription(int elementAddress, int modelId, int address) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addSubscription$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[elementAddress, modelId, address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Remove a subscription address from a model on a given element address.
  Future<bool> removeSubscription(int elementAddress, int modelId, int address) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeSubscription$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[elementAddress, modelId, address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Set publication for a model on a given element address.
  Future<bool> setPublication(int elementAddress, int modelId, int publishAddress, int appKeyIndex, {int? ttl, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setPublication$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[elementAddress, modelId, publishAddress, appKeyIndex, ttl]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> connectProxy(String deviceId, int proxyUnicastAddress) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.connectProxy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, proxyUnicastAddress]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> disconnectProxy() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.disconnectProxy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> isProxyConnected() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.isProxyConnected$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> connectProvisioning(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.connectProvisioning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> disconnectProvisioning() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.disconnectProvisioning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> isProvisioningConnected() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.isProvisioningConnected$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Whether the native implementation can reliably populate `MeshMessage.address`
  /// (source address) for incoming Access messages.
  Future<bool> supportsRxSourceAddress() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.supportsRxSourceAddress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Clear persisted secure mesh state used for stable Access message sending.
  ///
  /// Intended for debugging and recovery (e.g. when switching Mesh DBs).
  Future<void> clearSecureStorage() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.clearSecureStorage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Enable/disable experimental RX metadata extraction on Android.
  ///
  /// When enabled, Android may use internal APIs (via reflection) to extract the
  /// source address for incoming Access messages. When disabled, Android will
  /// use only public APIs and `MeshMessage.address` may be null.
  ///
  /// On iOS this is a no-op.
  Future<void> setExperimentalRxMetadataEnabled(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setExperimentalRxMetadataEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class MeshFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onDeviceDiscovered(FlutterUnprovisionedDevice device);

  void onMessageReceived(MeshMessage message);

  /// A richer, forward-compatible RX event that carries best-effort metadata.
  ///
  /// This stream is controlled by this plugin's contract (rather than relying on
  /// internal/native library details) so apps can build stable logging and routing.
  void onRxAccessMessage(RxAccessMessage event);

  /// Provisioning lifecycle events (progress + OOB prompts).
  void onProvisioningEvent(ProvisioningEvent event);

  static void setUp(MeshFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onDeviceDiscovered$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final FlutterUnprovisionedDevice arg_device = args[0]! as FlutterUnprovisionedDevice;
          try {
            api.onDeviceDiscovered(arg_device);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onMessageReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final MeshMessage arg_message = args[0]! as MeshMessage;
          try {
            api.onMessageReceived(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onRxAccessMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final RxAccessMessage arg_event = args[0]! as RxAccessMessage;
          try {
            api.onRxAccessMessage(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onProvisioningEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ProvisioningEvent arg_event = args[0]! as ProvisioningEvent;
          try {
            api.onProvisioningEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
