// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.platojobs.nrf_mesh

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonGeneratedPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class RxMetadataStatus(val raw: Int) {
  AVAILABLE(0),
  UNAVAILABLE(1);

  companion object {
    fun ofRaw(raw: Int): RxMetadataStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ProvisioningEventType(val raw: Int) {
  STARTED(0),
  CAPABILITIES_RECEIVED(1),
  OOB_INPUT_REQUESTED(2),
  OOB_OUTPUT_REQUESTED(3),
  PROVISIONING_COMPLETED(4),
  FAILED(5);

  companion object {
    fun ofRaw(raw: Int): ProvisioningEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MeshNetwork (
  val networkId: String? = null,
  val name: String? = null,
  val networkKeys: List<NetworkKey>? = null,
  val appKeys: List<AppKey>? = null,
  val nodes: List<ProvisionedNode>? = null,
  val groups: List<MeshGroup>? = null,
  val provisioner: Provisioner? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MeshNetwork {
      val networkId = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val networkKeys = pigeonVar_list[2] as List<NetworkKey>?
      val appKeys = pigeonVar_list[3] as List<AppKey>?
      val nodes = pigeonVar_list[4] as List<ProvisionedNode>?
      val groups = pigeonVar_list[5] as List<MeshGroup>?
      val provisioner = pigeonVar_list[6] as Provisioner?
      return MeshNetwork(networkId, name, networkKeys, appKeys, nodes, groups, provisioner)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      networkId,
      name,
      networkKeys,
      appKeys,
      nodes,
      groups,
      provisioner,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MeshNetwork
    return PigeonGeneratedPigeonUtils.deepEquals(this.networkId, other.networkId) && PigeonGeneratedPigeonUtils.deepEquals(this.name, other.name) && PigeonGeneratedPigeonUtils.deepEquals(this.networkKeys, other.networkKeys) && PigeonGeneratedPigeonUtils.deepEquals(this.appKeys, other.appKeys) && PigeonGeneratedPigeonUtils.deepEquals(this.nodes, other.nodes) && PigeonGeneratedPigeonUtils.deepEquals(this.groups, other.groups) && PigeonGeneratedPigeonUtils.deepEquals(this.provisioner, other.provisioner)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.networkId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.name)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.networkKeys)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.appKeys)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.nodes)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.groups)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.provisioner)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NetworkKey (
  val keyId: String? = null,
  val key: String? = null,
  val index: Long? = null,
  val enabled: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NetworkKey {
      val keyId = pigeonVar_list[0] as String?
      val key = pigeonVar_list[1] as String?
      val index = pigeonVar_list[2] as Long?
      val enabled = pigeonVar_list[3] as Boolean?
      return NetworkKey(keyId, key, index, enabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyId,
      key,
      index,
      enabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NetworkKey
    return PigeonGeneratedPigeonUtils.deepEquals(this.keyId, other.keyId) && PigeonGeneratedPigeonUtils.deepEquals(this.key, other.key) && PigeonGeneratedPigeonUtils.deepEquals(this.index, other.index) && PigeonGeneratedPigeonUtils.deepEquals(this.enabled, other.enabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.keyId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.key)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.index)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.enabled)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AppKey (
  val keyId: String? = null,
  val key: String? = null,
  val index: Long? = null,
  val enabled: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppKey {
      val keyId = pigeonVar_list[0] as String?
      val key = pigeonVar_list[1] as String?
      val index = pigeonVar_list[2] as Long?
      val enabled = pigeonVar_list[3] as Boolean?
      return AppKey(keyId, key, index, enabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyId,
      key,
      index,
      enabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppKey
    return PigeonGeneratedPigeonUtils.deepEquals(this.keyId, other.keyId) && PigeonGeneratedPigeonUtils.deepEquals(this.key, other.key) && PigeonGeneratedPigeonUtils.deepEquals(this.index, other.index) && PigeonGeneratedPigeonUtils.deepEquals(this.enabled, other.enabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.keyId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.key)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.index)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.enabled)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Provisioner (
  val name: String? = null,
  val provisionerId: String? = null,
  val addressRange: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Provisioner {
      val name = pigeonVar_list[0] as String?
      val provisionerId = pigeonVar_list[1] as String?
      val addressRange = pigeonVar_list[2] as List<Long>?
      return Provisioner(name, provisionerId, addressRange)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      provisionerId,
      addressRange,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Provisioner
    return PigeonGeneratedPigeonUtils.deepEquals(this.name, other.name) && PigeonGeneratedPigeonUtils.deepEquals(this.provisionerId, other.provisionerId) && PigeonGeneratedPigeonUtils.deepEquals(this.addressRange, other.addressRange)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.name)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.provisionerId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.addressRange)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UnprovisionedDevice (
  val deviceId: String? = null,
  val name: String? = null,
  val rssi: Long? = null,
  val uuid: List<Long>? = null,
  /** Best-effort primary service UUID discovered (e.g. "1827" provisioning or "1828" proxy). */
  val serviceUuid: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UnprovisionedDevice {
      val deviceId = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long?
      val uuid = pigeonVar_list[3] as List<Long>?
      val serviceUuid = pigeonVar_list[4] as String?
      return UnprovisionedDevice(deviceId, name, rssi, uuid, serviceUuid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      name,
      rssi,
      uuid,
      serviceUuid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UnprovisionedDevice
    return PigeonGeneratedPigeonUtils.deepEquals(this.deviceId, other.deviceId) && PigeonGeneratedPigeonUtils.deepEquals(this.name, other.name) && PigeonGeneratedPigeonUtils.deepEquals(this.rssi, other.rssi) && PigeonGeneratedPigeonUtils.deepEquals(this.uuid, other.uuid) && PigeonGeneratedPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.name)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.rssi)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.uuid)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.serviceUuid)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProvisionedNode (
  val nodeId: String? = null,
  val name: String? = null,
  val unicastAddress: Long? = null,
  val uuid: List<Long>? = null,
  val elements: List<Element>? = null,
  val provisioned: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProvisionedNode {
      val nodeId = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val unicastAddress = pigeonVar_list[2] as Long?
      val uuid = pigeonVar_list[3] as List<Long>?
      val elements = pigeonVar_list[4] as List<Element>?
      val provisioned = pigeonVar_list[5] as Boolean?
      return ProvisionedNode(nodeId, name, unicastAddress, uuid, elements, provisioned)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nodeId,
      name,
      unicastAddress,
      uuid,
      elements,
      provisioned,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProvisionedNode
    return PigeonGeneratedPigeonUtils.deepEquals(this.nodeId, other.nodeId) && PigeonGeneratedPigeonUtils.deepEquals(this.name, other.name) && PigeonGeneratedPigeonUtils.deepEquals(this.unicastAddress, other.unicastAddress) && PigeonGeneratedPigeonUtils.deepEquals(this.uuid, other.uuid) && PigeonGeneratedPigeonUtils.deepEquals(this.elements, other.elements) && PigeonGeneratedPigeonUtils.deepEquals(this.provisioned, other.provisioned)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.nodeId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.name)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.unicastAddress)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.uuid)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.elements)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.provisioned)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Element (
  val address: Long? = null,
  val models: List<Model>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Element {
      val address = pigeonVar_list[0] as Long?
      val models = pigeonVar_list[1] as List<Model>?
      return Element(address, models)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      models,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Element
    return PigeonGeneratedPigeonUtils.deepEquals(this.address, other.address) && PigeonGeneratedPigeonUtils.deepEquals(this.models, other.models)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.address)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.models)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Model (
  val modelId: Long? = null,
  val modelName: String? = null,
  val publishable: Boolean? = null,
  val subscribable: Boolean? = null,
  val boundAppKeyIndexes: List<Long>? = null,
  val subscriptions: List<Long>? = null,
  val publication: Publication? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Model {
      val modelId = pigeonVar_list[0] as Long?
      val modelName = pigeonVar_list[1] as String?
      val publishable = pigeonVar_list[2] as Boolean?
      val subscribable = pigeonVar_list[3] as Boolean?
      val boundAppKeyIndexes = pigeonVar_list[4] as List<Long>?
      val subscriptions = pigeonVar_list[5] as List<Long>?
      val publication = pigeonVar_list[6] as Publication?
      return Model(modelId, modelName, publishable, subscribable, boundAppKeyIndexes, subscriptions, publication)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      modelId,
      modelName,
      publishable,
      subscribable,
      boundAppKeyIndexes,
      subscriptions,
      publication,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Model
    return PigeonGeneratedPigeonUtils.deepEquals(this.modelId, other.modelId) && PigeonGeneratedPigeonUtils.deepEquals(this.modelName, other.modelName) && PigeonGeneratedPigeonUtils.deepEquals(this.publishable, other.publishable) && PigeonGeneratedPigeonUtils.deepEquals(this.subscribable, other.subscribable) && PigeonGeneratedPigeonUtils.deepEquals(this.boundAppKeyIndexes, other.boundAppKeyIndexes) && PigeonGeneratedPigeonUtils.deepEquals(this.subscriptions, other.subscriptions) && PigeonGeneratedPigeonUtils.deepEquals(this.publication, other.publication)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.modelId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.modelName)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.publishable)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.subscribable)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.boundAppKeyIndexes)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.subscriptions)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.publication)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Publication (
  val address: Long? = null,
  val appKeyIndex: Long? = null,
  val ttl: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Publication {
      val address = pigeonVar_list[0] as Long?
      val appKeyIndex = pigeonVar_list[1] as Long?
      val ttl = pigeonVar_list[2] as Long?
      return Publication(address, appKeyIndex, ttl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      appKeyIndex,
      ttl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Publication
    return PigeonGeneratedPigeonUtils.deepEquals(this.address, other.address) && PigeonGeneratedPigeonUtils.deepEquals(this.appKeyIndex, other.appKeyIndex) && PigeonGeneratedPigeonUtils.deepEquals(this.ttl, other.ttl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.address)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.appKeyIndex)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.ttl)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MeshGroup (
  val groupId: String? = null,
  val name: String? = null,
  val address: Long? = null,
  val nodeIds: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MeshGroup {
      val groupId = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val address = pigeonVar_list[2] as Long?
      val nodeIds = pigeonVar_list[3] as List<String>?
      return MeshGroup(groupId, name, address, nodeIds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      groupId,
      name,
      address,
      nodeIds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MeshGroup
    return PigeonGeneratedPigeonUtils.deepEquals(this.groupId, other.groupId) && PigeonGeneratedPigeonUtils.deepEquals(this.name, other.name) && PigeonGeneratedPigeonUtils.deepEquals(this.address, other.address) && PigeonGeneratedPigeonUtils.deepEquals(this.nodeIds, other.nodeIds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.groupId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.name)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.address)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.nodeIds)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MeshMessage (
  val opcode: Long? = null,
  val address: Long? = null,
  val appKeyIndex: Long? = null,
  val parameters: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MeshMessage {
      val opcode = pigeonVar_list[0] as Long?
      val address = pigeonVar_list[1] as Long?
      val appKeyIndex = pigeonVar_list[2] as Long?
      val parameters = pigeonVar_list[3] as Map<String, Any?>?
      return MeshMessage(opcode, address, appKeyIndex, parameters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      opcode,
      address,
      appKeyIndex,
      parameters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MeshMessage
    return PigeonGeneratedPigeonUtils.deepEquals(this.opcode, other.opcode) && PigeonGeneratedPigeonUtils.deepEquals(this.address, other.address) && PigeonGeneratedPigeonUtils.deepEquals(this.appKeyIndex, other.appKeyIndex) && PigeonGeneratedPigeonUtils.deepEquals(this.parameters, other.parameters)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.opcode)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.address)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.appKeyIndex)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.parameters)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RxAccessMessage (
  val opcode: Long? = null,
  /** Access message parameters (raw bytes). */
  val parameters: List<Long>? = null,
  /** Best-effort source address (unicast), if available. */
  val source: Long? = null,
  /** Best-effort destination address, if available. */
  val destination: Long? = null,
  val metadataStatus: RxMetadataStatus? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RxAccessMessage {
      val opcode = pigeonVar_list[0] as Long?
      val parameters = pigeonVar_list[1] as List<Long>?
      val source = pigeonVar_list[2] as Long?
      val destination = pigeonVar_list[3] as Long?
      val metadataStatus = pigeonVar_list[4] as RxMetadataStatus?
      return RxAccessMessage(opcode, parameters, source, destination, metadataStatus)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      opcode,
      parameters,
      source,
      destination,
      metadataStatus,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RxAccessMessage
    return PigeonGeneratedPigeonUtils.deepEquals(this.opcode, other.opcode) && PigeonGeneratedPigeonUtils.deepEquals(this.parameters, other.parameters) && PigeonGeneratedPigeonUtils.deepEquals(this.source, other.source) && PigeonGeneratedPigeonUtils.deepEquals(this.destination, other.destination) && PigeonGeneratedPigeonUtils.deepEquals(this.metadataStatus, other.metadataStatus)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.opcode)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.parameters)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.source)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.destination)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.metadataStatus)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProvisioningParameters (
  val deviceName: String? = null,
  val oobMethod: Long? = null,
  val oobData: String? = null,
  val enablePrivacy: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProvisioningParameters {
      val deviceName = pigeonVar_list[0] as String?
      val oobMethod = pigeonVar_list[1] as Long?
      val oobData = pigeonVar_list[2] as String?
      val enablePrivacy = pigeonVar_list[3] as Boolean?
      return ProvisioningParameters(deviceName, oobMethod, oobData, enablePrivacy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceName,
      oobMethod,
      oobData,
      enablePrivacy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProvisioningParameters
    return PigeonGeneratedPigeonUtils.deepEquals(this.deviceName, other.deviceName) && PigeonGeneratedPigeonUtils.deepEquals(this.oobMethod, other.oobMethod) && PigeonGeneratedPigeonUtils.deepEquals(this.oobData, other.oobData) && PigeonGeneratedPigeonUtils.deepEquals(this.enablePrivacy, other.enablePrivacy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.deviceName)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.oobMethod)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.oobData)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.enablePrivacy)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProvisioningEvent (
  val deviceId: String? = null,
  val type: ProvisioningEventType? = null,
  val message: String? = null,
  val progress: Long? = null,
  val attentionTimer: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProvisioningEvent {
      val deviceId = pigeonVar_list[0] as String?
      val type = pigeonVar_list[1] as ProvisioningEventType?
      val message = pigeonVar_list[2] as String?
      val progress = pigeonVar_list[3] as Long?
      val attentionTimer = pigeonVar_list[4] as Long?
      return ProvisioningEvent(deviceId, type, message, progress, attentionTimer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      type,
      message,
      progress,
      attentionTimer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProvisioningEvent
    return PigeonGeneratedPigeonUtils.deepEquals(this.deviceId, other.deviceId) && PigeonGeneratedPigeonUtils.deepEquals(this.type, other.type) && PigeonGeneratedPigeonUtils.deepEquals(this.message, other.message) && PigeonGeneratedPigeonUtils.deepEquals(this.progress, other.progress) && PigeonGeneratedPigeonUtils.deepEquals(this.attentionTimer, other.attentionTimer)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.type)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.message)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.progress)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.attentionTimer)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GenericOnOffSet (
  val state: Boolean? = null,
  val transitionTime: Long? = null,
  val delay: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GenericOnOffSet {
      val state = pigeonVar_list[0] as Boolean?
      val transitionTime = pigeonVar_list[1] as Long?
      val delay = pigeonVar_list[2] as Long?
      return GenericOnOffSet(state, transitionTime, delay)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      transitionTime,
      delay,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GenericOnOffSet
    return PigeonGeneratedPigeonUtils.deepEquals(this.state, other.state) && PigeonGeneratedPigeonUtils.deepEquals(this.transitionTime, other.transitionTime) && PigeonGeneratedPigeonUtils.deepEquals(this.delay, other.delay)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.state)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.transitionTime)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.delay)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GenericLevelSet (
  val level: Long? = null,
  val transitionTime: Long? = null,
  val delay: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GenericLevelSet {
      val level = pigeonVar_list[0] as Long?
      val transitionTime = pigeonVar_list[1] as Long?
      val delay = pigeonVar_list[2] as Long?
      return GenericLevelSet(level, transitionTime, delay)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      transitionTime,
      delay,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GenericLevelSet
    return PigeonGeneratedPigeonUtils.deepEquals(this.level, other.level) && PigeonGeneratedPigeonUtils.deepEquals(this.transitionTime, other.transitionTime) && PigeonGeneratedPigeonUtils.deepEquals(this.delay, other.delay)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.level)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.transitionTime)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.delay)
    return result
  }
}
private open class PigeonGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RxMetadataStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProvisioningEventType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MeshNetwork.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NetworkKey.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppKey.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Provisioner.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UnprovisionedDevice.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProvisionedNode.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Element.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Model.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Publication.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MeshGroup.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MeshMessage.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RxAccessMessage.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProvisioningParameters.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProvisioningEvent.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GenericOnOffSet.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GenericLevelSet.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RxMetadataStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ProvisioningEventType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is MeshNetwork -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NetworkKey -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AppKey -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is Provisioner -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is UnprovisionedDevice -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ProvisionedNode -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is Element -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is Model -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is Publication -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is MeshGroup -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is MeshMessage -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is RxAccessMessage -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ProvisioningParameters -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is ProvisioningEvent -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is GenericOnOffSet -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is GenericLevelSet -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeshApi {
  fun createNetwork(name: String): MeshNetwork
  fun loadNetwork(): MeshNetwork
  fun saveNetwork(): Boolean
  fun exportNetwork(path: String): Boolean
  fun importNetwork(path: String): Boolean
  fun startScan()
  fun stopScan()
  fun provisionDevice(device: UnprovisionedDevice, params: ProvisioningParameters): ProvisionedNode
  fun sendMessage(message: MeshMessage)
  fun getNodes(): List<ProvisionedNode>
  fun removeNode(nodeId: String)
  fun createGroup(name: String): MeshGroup
  fun getGroups(): List<MeshGroup>
  fun addNodeToGroup(nodeId: String, groupId: String)
  /** Bind an AppKey to a model on a given element address. */
  fun bindAppKey(elementAddress: Long, modelId: Long, appKeyIndex: Long): Boolean
  /** Unbind an AppKey from a model on a given element address. */
  fun unbindAppKey(elementAddress: Long, modelId: Long, appKeyIndex: Long): Boolean
  /** Add a subscription address to a model on a given element address. */
  fun addSubscription(elementAddress: Long, modelId: Long, address: Long): Boolean
  /** Remove a subscription address from a model on a given element address. */
  fun removeSubscription(elementAddress: Long, modelId: Long, address: Long): Boolean
  /** Set publication for a model on a given element address. */
  fun setPublication(elementAddress: Long, modelId: Long, publishAddress: Long, appKeyIndex: Long, ttl: Long?): Boolean
  fun connectProxy(deviceId: String, proxyUnicastAddress: Long): Boolean
  fun disconnectProxy(): Boolean
  fun isProxyConnected(): Boolean
  /**
   * Whether the native implementation can reliably populate `MeshMessage.address`
   * (source address) for incoming Access messages.
   */
  fun supportsRxSourceAddress(): Boolean
  /**
   * Clear persisted secure mesh state used for stable Access message sending.
   *
   * Intended for debugging and recovery (e.g. when switching Mesh DBs).
   */
  fun clearSecureStorage()
  /**
   * Enable/disable experimental RX metadata extraction on Android.
   *
   * When enabled, Android may use internal APIs (via reflection) to extract the
   * source address for incoming Access messages. When disabled, Android will
   * use only public APIs and `MeshMessage.address` may be null.
   *
   * On iOS this is a no-op.
   */
  fun setExperimentalRxMetadataEnabled(enabled: Boolean)

  companion object {
    /** The codec used by MeshApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
    /** Sets up an instance of `MeshApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeshApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createNetwork$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.createNetwork(nameArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.loadNetwork$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.loadNetwork())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.saveNetwork$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.saveNetwork())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.exportNetwork$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.exportNetwork(pathArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.importNetwork$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.importNetwork(pathArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startScan()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScan()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.provisionDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as UnprovisionedDevice
            val paramsArg = args[1] as ProvisioningParameters
            val wrapped: List<Any?> = try {
              listOf(api.provisionDevice(deviceArg, paramsArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.sendMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as MeshMessage
            val wrapped: List<Any?> = try {
              api.sendMessage(messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getNodes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNodes())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeNode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeNode(nodeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.createGroup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.createGroup(nameArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.getGroups$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGroups())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addNodeToGroup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as String
            val groupIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.addNodeToGroup(nodeIdArg, groupIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.bindAppKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val elementAddressArg = args[0] as Long
            val modelIdArg = args[1] as Long
            val appKeyIndexArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.bindAppKey(elementAddressArg, modelIdArg, appKeyIndexArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.unbindAppKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val elementAddressArg = args[0] as Long
            val modelIdArg = args[1] as Long
            val appKeyIndexArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.unbindAppKey(elementAddressArg, modelIdArg, appKeyIndexArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.addSubscription$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val elementAddressArg = args[0] as Long
            val modelIdArg = args[1] as Long
            val addressArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.addSubscription(elementAddressArg, modelIdArg, addressArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.removeSubscription$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val elementAddressArg = args[0] as Long
            val modelIdArg = args[1] as Long
            val addressArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.removeSubscription(elementAddressArg, modelIdArg, addressArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setPublication$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val elementAddressArg = args[0] as Long
            val modelIdArg = args[1] as Long
            val publishAddressArg = args[2] as Long
            val appKeyIndexArg = args[3] as Long
            val ttlArg = args[4] as Long?
            val wrapped: List<Any?> = try {
              listOf(api.setPublication(elementAddressArg, modelIdArg, publishAddressArg, appKeyIndexArg, ttlArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.connectProxy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val proxyUnicastAddressArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.connectProxy(deviceIdArg, proxyUnicastAddressArg))
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.disconnectProxy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.disconnectProxy())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.isProxyConnected$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isProxyConnected())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.supportsRxSourceAddress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.supportsRxSourceAddress())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.clearSecureStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearSecureStorage()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nrf_mesh_flutter.MeshApi.setExperimentalRxMetadataEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setExperimentalRxMetadataEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MeshFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MeshFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
  }
  fun onDeviceDiscovered(deviceArg: UnprovisionedDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onDeviceDiscovered$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onMessageReceived(messageArg: MeshMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onMessageReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * A richer, forward-compatible RX event that carries best-effort metadata.
   *
   * This stream is controlled by this plugin's contract (rather than relying on
   * internal/native library details) so apps can build stable logging and routing.
   */
  fun onRxAccessMessage(eventArg: RxAccessMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onRxAccessMessage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Provisioning lifecycle events (progress + OOB prompts). */
  fun onProvisioningEvent(eventArg: ProvisioningEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nrf_mesh_flutter.MeshFlutterApi.onProvisioningEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
